File-Formats/installation-and-upgrade/System-Requirements.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-62482">https://syncfusion.atlassian.net/browse/WF-62482</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Modify operating system details in system requirements page.
</td>
</tr>
<tr>
<td>
Solution
</td>
<td>
Updated operating system details in the system requirement page.
</td>
</tr>
</table>
=> WF-62482-Modify operating system details in system requirements page

File-Formats/PDF/Open-and-Save-PDF-file-in-C-Sharp-VB-NET.md
Need to update the UG with the other possible error messages while loading the invalid PDF document.
Old UG task link: https://syncfusion.atlassian.net/browse/WF-62254
ticket details: https://support.syncfusion.com/agent/tickets/362585
=> WF-62402 Need to update the existing UG

File-Formats/PDF/Converting-HTML-to-PDF.md
Hi,
I have added content changes for the UG 'Steps to disable IE warning while performing HTML To PDF using the IE rendering engine'. Kindly go through and provide your feedback for the same.
Please refer the documentation task details:
https://syncfusion.atlassian.net/browse/DOC-4114
Regards,
Irfana J.
=> WF-62492 Steps to disable IE warning while performing HTML To PDF using the IE rendering engine

File-Formats/DocIO/FAQ.md, File-Formats/DocIO/Working-with-Word-document.md, File-Formats/PDF/Convert-HTML-To-PDF/WebKit.md, File-Formats/PDF/Create-PDF-file-in-C-Sharp-VB-NET.md, File-Formats/PDF/Create-PDF-file-in-WPF.md, File-Formats/XlsIO/Excel-to-PDF-Conversion.md, File-Formats/XlsIO/Working-with-Charts.md
Hi @ChristoIssac,
Fixed Weblink validator broken links, merge these changes.
Regards,
Gowthaman
=> SEO-1937_Broken_links

File-Formats/XlsIO/Create-read-edit-excel-files-in-asp-net-core-c-sharp.md, File-Formats/XlsIO/Create-read-edit-excel-files-in-uwp-c-sharp.md, File-Formats/XlsIO/create-read-edit-excel-files-in-asp-net-c-sharp.md, File-Formats/XlsIO/create-read-edit-excel-files-in-asp-net-mvc-c-sharp.md, File-Formats/XlsIO/create-read-edit-excel-files-in-xamarin-c-sharp.md
Hi @Mohan2401,
Regards,
Keerthi.
=> WF-62534 - XlsIO Sample Links - HotFix

File-Formats/XlsIO/Create-read-edit-excel-files-in-asp-net-core-c-sharp.md, File-Formats/XlsIO/Create-read-edit-excel-files-in-uwp-c-sharp.md, File-Formats/XlsIO/create-read-edit-excel-files-in-asp-net-c-sharp.md, File-Formats/XlsIO/create-read-edit-excel-files-in-asp-net-mvc-c-sharp.md, File-Formats/XlsIO/create-read-edit-excel-files-in-xamarin-c-sharp.md
=> WF-62534 - XlsIO Sample Links - Master

File-Formats/DocIO/Accepting-or-Rejecting-Track-Changes.md, File-Formats/DocIO/Applying-Watermark.md, File-Formats/DocIO/Getting-Started.md, File-Formats/DocIO/Working-with-Mathematical-Equation.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-62548">https://syncfusion.atlassian.net/browse/WF-62548</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
</td>
</tr>
<tr>
<td>
Changes done
</td>
<td>
Added GitHub sample link in UG documentation in below pages,
- Getting Started
- Mathematical Equation
- Watermark
- Track Changes
</td>
</tr>
</table>
=> WF-62548-Add GitHub sample link in UG documentation

File-Formats/XlsIO/Excel-to-PDF-Conversion.md
=> WF-56929 - Update ExcelToPDF UnsupportedList - XlsIO

File-Formats/XlsIO/Working-with-Formulas.md
EJDOTNETCORE-3368-Added UNIQUE Formula with Description into UG
=> EJDOTNETCORE-3368-Add-New-UNIQUE-Formual-into-UG

File-Formats-toc.html, File-Formats/DocIO/Working-with-Footnotes-and-endnotes.md
WF-62403 - Delete Footnote/Endnote from the Word document using DocIO
=> WF-62403 - Delete Footnote/Endnote from the Word document using DocIO

File-Formats/PDF/Working-with-Document.md
Hi @chinnumuniyappan 
I have added UG documentation for Embed all the non-embedded fonts support.Please review and merge the ug changes
Please find the content review task link below,
https://syncfusion.atlassian.net/browse/DOC-4156?oldIssueView=true
Regards,
Ravikumar.
=> WF-62642 Add UG documentation for Embed all the non-embedded fonts support

File-Formats/DocIO/Working-With-Content-Controls.md
Merge pull request #15 from syncfusion-content/WF-61451-EditContentControlText
WF-61451 - Add information about editing content control text in the Word document
=> WF-61451 - Add information about to edit content control text in the Word document

File-Formats/PDF/Working-with-PDF-Conformance.md
Hi @chinnumuniyappan 
Please review the UG documentation changes
Task ID: https://syncfusion.atlassian.net/browse/WF-62634?oldIssueView=true
Content Reviewed Task is linked in the above UG task for your reference
Regards,
Moorthy K
=> WF-62634 Add UG documentation to convert the PDFA document to a PDF document

File-Formats/DocIO/Working-with-Word-document.md
WF-62510, WF-62511 - Split Word document by Section, Headings
=> WF-62510, WF-62511 - Split Word document by Section, Headings

File-Formats/DocIO/Working-with-Word-document.md
WF-62513,WF-62512 How to split the Word document by using the placeholder text and bookmark.
https://syncfusion.atlassian.net/browse/WF-62512
https://syncfusion.atlassian.net/browse/WF-62513
=> WF-62513,WF-62512 How to split the Word document by using the placeholder text and bookmark.

File-Formats/DocIO/Getting-Started.md, File-Formats/DocIO/Loading-and-Saving-document.md, File-Formats/DocIO/Working-with-Bookmarks.md, File-Formats/DocIO/Working-with-Comments.md, File-Formats/DocIO/Working-with-Find-and-Replace.md, File-Formats/DocIO/Working-with-Footnotes-and-endnotes.md, File-Formats/DocIO/Working-with-Form-Fields.md, File-Formats/DocIO/Working-with-Security.md, File-Formats/DocIO/Working-with-Table-Of-Contents.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-62692">https://syncfusion.atlassian.net/browse/WF-62692</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
</td>
</tr>
<tr>
<td>
Changes done
</td>
<td>
Added GitHub sample link in UG documentation in below pages, 
<p></p>
- Bookmarks
- Comments
- Find-and-Replace
- Footnotes-and-Endnotes
- Form-Fields
- Security
- Table-Of-Contents
</td>
</tr>
</table>
=> WF-62692-Add UG documentation changes for GitHub link

File-Formats/XlsIO/Chart-to-Image-Conversion.md, File-Formats/XlsIO/Custom-XML-Support.md, File-Formats/XlsIO/Excel-to-JSON-Conversion.md, File-Formats/XlsIO/Excel-to-ODS-Conversion.md, File-Formats/XlsIO/Excel-to-PDF-Conversion.md, File-Formats/XlsIO/Excel-to-PDF-Converter-Settings.md, File-Formats/XlsIO/Loading-and-Saving-Workbook.md, File-Formats/XlsIO/Security.md, File-Formats/XlsIO/Working-with-Cell-or-Range-Formatting.md, File-Formats/XlsIO/Working-with-Charts.md, File-Formats/XlsIO/Working-with-Conditional-Formatting.md, File-Formats/XlsIO/Working-with-Data-Validation.md, File-Formats/XlsIO/Working-with-Data.md, File-Formats/XlsIO/Working-with-Drawing-Objects.md, File-Formats/XlsIO/Working-with-Excel-Tables.md, File-Formats/XlsIO/Working-with-Excel-Worksheet.md, File-Formats/XlsIO/Working-with-Formulas.md, File-Formats/XlsIO/Working-with-Macros.md, File-Formats/XlsIO/Working-with-Pictures.md, File-Formats/XlsIO/Working-with-Pivot-Charts.md, File-Formats/XlsIO/Working-with-Pivot-Tables.md, File-Formats/XlsIO/Working-with-Template-Markers.md, File-Formats/XlsIO/Worksheet-Cells-Manipulation.md, File-Formats/XlsIO/Worksheet-Rows-and-Columns-Manipulation.md, File-Formats/XlsIO/Worksheet-to-Image-Conversion.md
=> WF-62664-GitHubSampleLinks-XlsIO-HF

File-Formats/XlsIO/Working-with-Data.md
Kindly review and merge these changes.
**Ticket ID** - https://support.syncfusion.com/agent/tickets/369056 
Regards,
Keerthi.
=> WF-62697-SupportedStyles-XlsIO-HF

File-Formats/PDF/Create-PDF-document-in-Blazor.md
Hi Team,
I have updated the changes from the following two pull request into this pull request since the CI is not running. Please go through the changes and provide your feedback.
https://github.com/syncfusion-content/fileformat-docs/pull/189
https://github.com/syncfusion-content/fileformat-docs/pull/190
Regards,
Irfana J.
=> EJDOTNETCORE-3402 - Changed syntax for code in PDF_blazor

File-Formats/DocIO/Create-Word-document-in-MAUI.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-maui.md
<h4 id="feature-description">Kindly review the below merge request and let me know if you have any concerns,</h4>
<table style="width: 155px;">
<tbody>
<tr style="height: 86px;">
<td style="width: 37.7396px; height: 86px;">
<h4 id="feature-description">Task link</h4>
</td>
<td style="width: 121.26px; height: 86px;">
<p><a href="https://syncfusion.atlassian.net/browse/WF-62494" rel="nofollow">https://syncfusion.atlassian.net/browse/WF-62494</a></p>
</td>
</tr>
<tr style="height: 56.7917px;">
<td style="width: 37.7396px; height: 56.7917px;">
<h4 id="feature-description">Description</h4>
</td>
<td style="width: 121.26px; height: 56.7917px;">Modify UG documentation for .NET MAUI for DocIO and Presentation.</td>
</tr>
<tr style="height: 88px;">
<td style="width: 37.7396px; height: 88px;">
<h4 …
=> WF-62494-Modify UG documentation for .NET MAUI (mac-catalyst)

File-Formats/DocIO/FAQ.md, File-Formats/DocIO/NuGet-Packages-Required.md, File-Formats/DocIO/word-to-pdf.md
-Update SkiaSharp NuGet information for Word to PDF in Portable platforms
=> EJDOTNETCORE-3482-Update SkiaSharp NuGet information for Word to PDF in Portable platforms

File-Formats/DocIO/Working-with-Word-document.md
WF-62513,WF-62512 How to split the Word document by using the placeholder text and bookmark.
=> WF-62513, WF-62512 - How to split the Word document by using the placeholder text and bookmark.

File-Formats/XlsIO/Working-with-Formulas.md
Add new Excel 365 formulas in UG documentation with description.
1. XLOOKUP
2. LET
3. XMATCH
4. VALUETOTEXT
5. ARRAYTOTEXT
=> EJDOTNETCORE-3368-Added-Five-New-Formula-to-UG

File-Formats/PDF/Convert-HTML-To-PDF/Blink.md, File-Formats/PDF/Convert-HTML-To-PDF/IE.md, File-Formats/PDF/Convert-HTML-To-PDF/WebKit.md, File-Formats/PDF/Converting-HTML-to-PDF.md, File-Formats/PDF/Overview.md
Description
Need to add the following notes in the following UG locations:
Note to be added:
Note: * Starting with v20.1.0.x, if you reference Syncfusion HTML converter assemblies from trial setup or from the NuGet feed, include a license key in your projects. Refer to [link](https://help.syncfusion.com/file-formats/licensing/licensing) to learn how to generate and register a Syncfusion license key in your application to use the components without trail message.
UG locations to be updated:
https://help.syncfusion.com/file-formats/pdf/overview
https://help.syncfusion.com/file-formats/pdf/converting-html-to-pdf
https://help.syncfusion.com/file-formats/pdf/convert-html-to-pdf/webkit
https://help.syncfusion.com/file-formats/pdf/convert-html-to-pdf/blink …
=> WF-62824 Need to add Notes in the following UG locations - dev

File-Formats/DocIO/Working-with-Word-document.md
- We have faced the conflict while merging hotfix changes into development in this PR [188](https://github.com/syncfusion-content/fileformat-docs/pull/188)
- We have resolved conflict in Hotfix branch due to the release content in development branch mismatched with hotfix branch.
- Reverted the conflict changes from hotfix branch.
- Once changes merged into development, again will committ the reverted changes in hotfix branch.
=> WF-62892-Resolved conflict in Hotfix branch

File-Formats/PDF/Working-with-DigitalSignature.md
WF-61918  resolved conflicts in digitalsignature.md
I have added changes related to resolve CI conflicts in merging UG while automation. The base source development is outdated when compared to the hotfix branch and hence it caused the conflict. I have updated the digitalsignature.md file and committed the changes. Kindly go through and provide your feedback for the same.
=> WF-61918  resolved conflicts in digitalsignature.md

File-Formats/DocIO/Working-with-Word-document.md
- Due to conflict while merging hotfix changes into development in this PR [188](https://github.com/syncfusion-content/fileformat-docs/pull/188), we have reverted the conflicted changes from hotfix branch.
- Now it is merged into development, so again we have added the reverted changes into hotfix.
MR used for reverting the conflict- https://github.com/syncfusion-content/fileformat-docs/pull/231
=> WF-62892-Added the reverted changes into hotfix

File-Formats/DocIO/Getting-Started.md, File-Formats/DocIO/Loading-and-Saving-document.md, File-Formats/DocIO/Working-with-Bookmarks.md, File-Formats/DocIO/Working-with-Charts.md, File-Formats/DocIO/Working-with-Fields.md, File-Formats/DocIO/Working-with-Find-and-Replace.md, File-Formats/DocIO/Working-with-Paragraph.md, File-Formats/DocIO/Working-with-Sections.md, File-Formats/DocIO/Working-with-Table-Of-Contents.md, File-Formats/DocIO/Working-with-Tables.md, File-Formats/DocIO/mail-merge/mail-merge-events.md, File-Formats/DocIO/mail-merge/simple-mail-merge.md, File-Formats/DocIO/word-to-pdf.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-62621">https://syncfusion.atlassian.net/browse/WF-62621</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Add See Also content for all UG pages.
</td>
</tr>
<tr>
<td>
Changes done
</td>
<td>
Added the published kb links as See Also in corresponding UG pages.
</td>
</tr>
</table>
=> WF-62621-Add See Also content for all UG pages

File-Formats/DocIO/Word-document/Iterating-Word-document-elements.md, File-Formats/DocIO/Word-document/Merging-Word-documents.md, File-Formats/DocIO/Working-with-Word-document.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-62949">https://syncfusion.atlassian.net/browse/WF-62949</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Divide the existing Working With Word Document UG documentation as sub page documents.
</td>
</tr>
<tr>
<td>
Changes done
</td>
<td>
Removed existing content in Word document page. <br/>
Added heading for each use cases in Iterating Word document element and Merging Word documents page.
</td>
</tr>
</table>
=> WF-62949-Removed existing content in Word document page

File-Formats/PDF/Convert-HTML-To-PDF/Blink.md, File-Formats/PDF/Convert-HTML-To-PDF/IE.md, File-Formats/PDF/Convert-HTML-To-PDF/WebKit.md, File-Formats/PDF/Converting-HTML-to-PDF.md, File-Formats/PDF/NuGet-Packages-Required.md, File-Formats/PDF/Overview.md, File-Formats/PDF/Working-with-OCR/Dot-NET-Core.md, File-Formats/PDF/Working-with-OCR/Dot-NET-Framework.md
WF-63019 Updated UG Changes for HTML Converter and OCR processor
=> WF-63019 Updated UG Changes for HTML Converter and OCR processor

File-Formats/PDF/Convert-HTML-To-PDF/Blink.md, File-Formats/PDF/Convert-HTML-To-PDF/IE.md, File-Formats/PDF/Convert-HTML-To-PDF/WebKit.md, File-Formats/PDF/Converting-HTML-to-PDF.md, File-Formats/PDF/NuGet-Packages-Required.md, File-Formats/PDF/Overview.md, File-Formats/PDF/Working-with-OCR/Dot-NET-Core.md, File-Formats/PDF/Working-with-OCR/Dot-NET-Framework.md
WF-63019 Updated UG Changes for HTML Converter and OCR processor - master
=> WF-63019 Updated UG Changes for HTML Converter and OCR processor - master

File-Formats-toc.html, File-Formats/XlsIO/FAQ.md, File-Formats/XlsIO/faqs/does-xlsio-support-working-with-excel-files-in-net6.md, File-Formats/XlsIO/faqs/how-to-convert-the-required-range-in-excel-to-pdf.md, File-Formats/XlsIO/faqs/how-to-search-a-value-in-only-specific-columns-of-an-Excel-worksheet.md
=> WF-62638-Search-in-entire-column

File-Formats/PDF/Convert-HTML-To-PDF/Blink.md, File-Formats/PDF/Convert-HTML-To-PDF/WebKit.md
WF-62824 added Htmltopdf converter notes details- hotfix
=> WF-62824 added Htmltopdf converter notes details- hotfix

File-Formats/PDF/Working-with-Annotations.md
=> SEO-2161-Interlinking and new URL changes

File-Formats/XlsIO/Chart-to-Image-Conversion.md, File-Formats/XlsIO/Excel-to-JSON-Conversion.md, File-Formats/XlsIO/Worksheet-to-Image-Conversion.md
**Keywords Considered:**
1. worksheet to image c#
2. excel to image c#
3. convert specific worksheet cells or range to image
4. excel chart to image
5. excel to json
Regards,
Keerthi.
=> WF-63001 - XlsIO SEO changes for Keywords - Hotfix

File-Formats/XlsIO/Excel-to-PDF-Conversion.md
**Keywords Considered:**
excel to pdf c# without office
=> WF-63000 - XlsIO SEO changes for Keywords - HotFix

File-Formats/XlsIO/Working-with-Pictures.md
=> WF-63048 - Image In Merged Region - HotFix - XlsIO

File-Formats/XlsIO/Improving-Performance.md
**Changes Made:**
Declared rowCount and colCount variables in code snippet, as per the request in support ticket https://support.syncfusion.com/agent/tickets/376552 
Regards,
Keerthi.
=> WF-63288 - Declare Variables - XlsIO - HotFix

File-Formats-toc.html, File-Formats/XlsIO/FAQ.md, File-Formats/XlsIO/faqs/how-to-read-filtered-rows-in-excel.md
Kindly merge these changes to resolve conflicts reported by the documentation team in hotfix to development automation.
https://github.com/syncfusion-content/fileformat-docs/pull/284
Regards,
Keerthi.
=> WF-63277 - Resolve XlsIO Conflicts - HotFix

File-Formats/DocIO/Create-Word-document-in-MAUI.md, File-Formats/DocIO/Create-Word-document-in-WinUI.md
Hi Team
I have made the ug changes in winui and maui word library. Please review and merge it.
Regards,
Mallika
=> SEO-2198: .NET MAUI and WinUI word - UG changes

File-Formats/XlsIO/Create-read-edit-excel-files-in-maui-c-sharp.md
Hi All,
Kindy review the changes and let me know your feedback.
Regards,
Keerthi
=> WF-63458-XlsIOMAUI-HF

File-Formats/PDF/Create-PDF-file-in-C-Sharp-VB-NET.md
Hi Sir, 
Kindly review the changes and let me know the feedback for the same. Please find the changes from below, 
- Added the given keywords in the respective place to improvise the UG documentation.
- Add the keywords topic in the header section.
Regards,
Sowmiya L
=> EJDOTNETCORE-3660 - Improve existing UG page (Getting Started PDF) - Hotfix

File-Formats/PDF/Convert-HTML-To-PDF/Blink.md
EJDOTNETCORE-3674 Need to update the additional dependency details for Latest BlinkBinariesLinux prerequisites
=> EJDOTNETCORE-3674 Need to update the additional dependency details for Latest BlinkBinariesLinux prerequisites

File-Formats/Presentation/Document-Object-Model.md, File-Formats/Presentation/Getting-Started.md, File-Formats/Presentation/Working-with-Macros.md, File-Formats/Presentation/Working-with-list.md
Worked on site audit issues, merge these changes.
Regards,
Gowthaman
=> SEO-2344_Site_Audit_Issues

File-Formats/DocIO/Assemblies-Required.md, File-Formats/DocIO/NuGet-Packages-Required.md, File-Formats/DocIO/word-to-image.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-63101">https://syncfusion.atlassian.net/browse/WF-63101</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Add Word to Image code snippets in UG documentation.
</td>
</tr>
<tr>
<td>
Solution
</td>
<td>
1. Added code snippet of Word to Image in ASP.NET Core and Xamarin platform. <br/>
2. Added Nugets and assemblies required for Word to Image.<br/>
3. Modify tips and added points in notes in the Word to image page.
</td>
</tr>
</table>
=> WF-63101-Add Word to Image code snippets in UG documentation

File-Formats/PDF/Working-with-OCR/Dot-NET-Core.md, File-Formats/PDF/Working-with-OCR/Dot-NET-Framework.md
Hi Team,
I have added UG changes for the task 'Create UG documentation for Image OCR to Pdf Document'.
Regards,
Jeyalakshmi T
=> WF-63677 Create UG documentation for Image OCR to Pdf Document

File-Formats/PDF/Working-with-OCR/Dot-NET-Core.md
Created UG documentation for OCR.NET library
=> WF-63633 Update UG documentation for OCR.NET library

File-Formats/PDF/Convert-HTML-To-PDF/Blink.md, File-Formats/PDF/Converting-HTML-to-PDF.md
Hi Team,
I have added UG changes for the task 'Update UG and KB documentation for HTML conversion in AWS with new NuGet package'.
Regards,
Jeyalakshmi T
=> WF-63634 Update UG and KB documentation for HTML conversion in AWS with new NuGet package

File-Formats/PDF/Working-with-Annotations.md
Create UG documentation for flattening annotation without calling save method
=> WF-63236 Create UG documentation for flattening annotation without calling save method

File-Formats/PDF/Working-with-Annotations.md
Created UG documentation for rich media annotation
=> WF-63629 Created UG documentation for rich media annotation

File-Formats/PDF/Convert-HTML-To-PDF/Blink.md
Hi Team
I have updated UG and KB documentation for HTML conversion in AWS with new NuGet package
Regards,
Karmegam
=> WF-63634-HtmlToPdfAwsBlink Update UG and KB documentation for HTML conversion in AWS with new NuGet package

File-Formats/PDF/Convert-HTML-To-PDF/Blink.md
WF-63634-HotFixHtmlToPdfAwsBlink Update UG and KB documentation for HTML conversion in AWS with new NuGet package
=> WF-63634-Update UG and KB documentation for HTML conversion in AWS with new NuGet package

File-Formats/Licensing/how-to-generate.md, File-Formats/Licensing/how-to-register-in-an-application.md, File-Formats/Licensing/licensing-errors.md, File-Formats/Licensing/licensing-faq/how-to-upgrade-from-trial-version-after-purchasing-a-license.md, File-Formats/Licensing/licensing-faq/registering-syncfusion-account-for-nuget-org-user.md, File-Formats/Licensing/overview.md, File-Formats/Upgrade/how-to-upgrade.md, File-Formats/installation/Installation-errors.md, File-Formats/installation/offline-installer/how-to-download.md, File-Formats/installation/web-installer/how-to-download.md
=> IN-18200-UG-Documentation-fileformat-hotfix

File-Formats/PDF/Working-with-Annotations.md, File-Formats/PDF/Working-with-PDF-Conformance.md
WF-63629-hotfix Alignment and Naming changes in UG document
=> WF-63629-hotfix Alignment and Naming changes in UG document

File-Formats/PDF/Convert-HTML-To-PDF/Blink.md, File-Formats/PDF/Convert-HTML-To-PDF/WebKit.md, File-Formats/PDF/Converting-HTML-to-PDF.md
Removed webkitpath and blinkpath in all the code snippets in UG.
=> WF-63759 Update UG for BlinkPath and WebKit for HTML converter

File-Formats/Licensing/how-to-generate.md, File-Formats/Licensing/how-to-register-in-an-application.md, File-Formats/Licensing/licensing-errors.md, File-Formats/Licensing/licensing-faq/how-to-upgrade-from-trial-version-after-purchasing-a-license.md, File-Formats/Licensing/licensing-faq/registering-syncfusion-account-for-nuget-org-user.md, File-Formats/Licensing/overview.md, File-Formats/Upgrade/how-to-upgrade.md, File-Formats/installation/Installation-errors.md, File-Formats/installation/offline-installer/how-to-download.md, File-Formats/installation/web-installer/how-to-download.md
=> IN-18200-UG-Documentation-fileformat-Link-changes-mas

File-Formats/XlsIO/Working-with-Data.md
**Tasks:**
https://syncfusion.atlassian.net/browse/WF-62730
https://syncfusion.atlassian.net/browse/WF-62695 
Regards,
Keerthi.
=> WF-62730 - Unsupported HTML symbols in the Import HTML Table

File-Formats-toc.html, File-Formats/XlsIO/FAQ.md, File-Formats/XlsIO/faqs/does-xlsio-support-multi-threading.md, File-Formats/XlsIO/faqs/how-to-apply-formatting-to-pivottable-in-Excel-protected-view.md, File-Formats/XlsIO/faqs/how-to-detect-merged-cells-in-Excel.md
**Tasks:** 
https://syncfusion.atlassian.net/browse/WF-44378 
https://syncfusion.atlassian.net/browse/WF-62416 
https://syncfusion.atlassian.net/browse/WF-45577 
Regards,
Keerthi.
=> WF-44378 - How to detect merged cells in an Excel worksheet using XlsIO

File-Formats/PDF/Working-with-OCR/Dot-NET-Core.md
Resolve the errors in OCR.NET UG documentation
Resolve the errors in UG documentation in code snippet
Resolve the alignment issues in OCR.NET UG documentation.
=> EJDOTNETCORE-3850 Resolve the errors in OCR.NET UG documentation

File-Formats/DocIO/Overview.md
Please review the file format overview changes.
Regards,
Sharly A.
=> SEO-2467 - File Format Docio Overview changes

File-Formats/Presentation/Getting-Started.md
Please review the file format presentation changes.
Regards,
Sharly A.
=> SEO-2467 - File Format Presentation changes

File-Formats/XlsIO/Overview.md
Please review the file format XLsLO overview changes.
Regards,
Sharly A
=> SEO-2467 - File Format XlsIO overview changes

File-Formats/PDF/Overview.md
Please review the file format pdf changes.
Regards,
Sharly A.
=> SEO-2467 - File Format PDF changes

File-Formats/XlsIO/Working-with-Cell-or-Range-Formatting.md, File-Formats/XlsIO/Working-with-Charts.md, File-Formats/XlsIO/Working-with-Drawing-Objects.md, File-Formats/XlsIO/Working-with-Formulas.md, File-Formats/XlsIO/Working-with-Template-Markers.md
Please review the file format Xlsio changes.
Regards,
Sharly A.
=> SEO-2467 - File Format Xlsio changes

File-Formats/DocIO/Getting-Started.md
Please review the file format docio getting started changes.
Regards,
Sharly A.
=> SEO-2467 - File Format Docio Getting Started changes

File-Formats/XlsIO/Security.md
Please review the file format Xlsio security changed.
Regards,
Sharly A.
=> SEO-2467 - File Format Xlsio security

File-Formats/Presentation/FAQ.md, File-Formats/Presentation/Presentation-to-PDF.md
<table>
<tbody>
<tr>
<td>
</td>
<td>
<p><a href="https://syncfusion.atlassian.net/browse/WF-63246">https://syncfusion.atlassian.net/browse/WF-63246</a></p>
</td>
</tr>
<tr>
<td>
</td>
<td>
<p>Add dependent NuGet packages details for PPTX to PDF conversion in Linux OS</p>
</td>
</tr>
<tr>
<td>
</td>
<td>
<p>Added content to what are the dependent NuGet packages details for PPTX to PDF conversion in Linux OS</p>
</td>
</tr>
</tbody>
</table>
<p><br /><br /></p>
=> WF-63246-Add dependent NuGet packages details for PPTX to PDF conversion in Linux OS

File-Formats/Presentation/create-read-edit-master-slide-and-layout-slide-in-c-sharp.md
PR - https://github.com/syncfusion-content/fileformat-docs/pull/440
=> WF-63706-How to set the background for master slide in the PowerPoint Presentation

File-Formats/DocIO/Working-with-Tables.md
<table>
<tbody>
<tr>
<td>
</td>
<td>
<p><a href="https://syncfusion.atlassian.net/browse/WF-62311">https://syncfusion.atlassian.net/browse/WF-62311</a></p>
</td>
</tr>
<tr>
<td>
</td>
<td>
<p>Add UG document to insert image into a table cell</p>
</td>
</tr>
<tr>
<td>
</td>
<td>
<p>Added code snippet to insert image into a table cell in all platforms.</p>
</td>
</tr>
</tbody>
</table>
=> WF-62311-Add information about how to insert image into a table cell

File-Formats/DocIO/Word-document/Merging-Word-documents.md, File-Formats/DocIO/Working-with-Charts.md, File-Formats/DocIO/Working-with-Paragraph.md, File-Formats/DocIO/Working-with-Table-Of-Contents.md, File-Formats/DocIO/mail-merge/simple-mail-merge.md, File-Formats/DocIO/word-to-pdf.md
<table>
<tbody>
<tr>
<td>
</td>
<td>
<p><a href="https://syncfusion.atlassian.net/browse/WF-59637">https://syncfusion.atlassian.net/browse/WF-59637</a></p>
</td>
</tr>
<tr>
<td>
</td>
<td>
<p>Add FAQ in all UG pages to redirect for KB</p>
</td>
</tr>
<tr>
<td>
</td>
<td>
<p>Added WinForms first 4 pages FAQ in all UG pages to redirect for KB</p>
</td>
</tr>
</tbody>
</table>
=> WF-59637-Add FAQ in all UG pages to redirect for KB

File-Formats/DocIO/word-to-image.md
<table>
<tbody>
<tr>
<td>
</td>
<td>
<p><a href="https://syncfusion.atlassian.net/browse/WF-63930">https://syncfusion.atlassian.net/browse/WF-63930</a></p>
</td>
</tr>
<tr>
<td>
</td>
<td>
<p>Modify the note content in Word to image UG documentation</p>
</td>
</tr>
<tr>
<td>
</td>
<td>
<p>Modified the note content in Word to image UG documentation</p>
</td>
</tr>
</tbody>
</table>
=> WF-63930-Modify the note content in Word to image UG documentation

File-Formats/Presentation/FAQ.md
<table>
<tbody>
<tr>
<td>
</td>
<td>
<p><a href="https://syncfusion.atlassian.net/browse/WF-63246">https://syncfusion.atlassian.net/browse/WF-63246</a></p>
</td>
</tr>
<tr>
<td>
</td>
<td>
<p>Add dependent NuGet packages details for PPTX to PDF conversion in Linux OS</p>
</td>
</tr>
<tr>
<td>
</td>
<td>
<p>Added content to what are the dependent NuGet packages details for PPTX to PDF conversion in Linux OS</p>
</td>
</tr>
</tbody>
</table>
<p><br /><br /></p>
=> WF-63246-Add dependent NuGet packages details for PPTX to PDF conversion in Linux OS 

File-Formats/Release-Notes/v19.1.0.56.md, File-Formats/Release-Notes/v19.1.0.57.md, File-Formats/Release-Notes/v19.1.0.58.md, File-Formats/Release-Notes/v19.1.0.59.md, File-Formats/Release-Notes/v19.1.0.64.md, File-Formats/Release-Notes/v19.1.0.65.md, File-Formats/Release-Notes/v19.1.0.66.md, File-Formats/Release-Notes/v19.1.0.67.md, File-Formats/Release-Notes/v19.1.0.69.md, File-Formats/Release-Notes/v19.2.0.46.md, File-Formats/Release-Notes/v19.2.0.47.md, File-Formats/Release-Notes/v19.2.0.48.md, File-Formats/Release-Notes/v19.2.0.49.md, File-Formats/Release-Notes/v19.2.0.51.md, File-Formats/Release-Notes/v19.2.0.56.md, File-Formats/Release-Notes/v19.2.0.57.md, File-Formats/Release-Notes/v19.2.0.59.md, File-Formats/Release-Notes/v19.2.0.60.md, File-Formats/Release-Notes/v19.2.0.62.md, File-Formats/Release-Notes/v19.3.0.44.md, File-Formats/Release-Notes/v19.3.0.45.md, File-Formats/Release-Notes/v19.3.0.46.md, File-Formats/Release-Notes/v19.3.0.47.md, File-Formats/Release-Notes/v19.3.0.48.md, File-Formats/Release-Notes/v19.3.0.56.md, File-Formats/Release-Notes/v19.3.0.57.md
Please find changes made on file formats release notes.
Regards,
@Scholar-jaruha
=> SEO-2447-File Formats Release notes

File-Formats/DocIO/word-to-image.md
PR - https://github.com/syncfusion-content/fileformat-docs/pull/491
=> WF-64205-Removed the unwanted changes

File-Formats/Presentation/Working-with-Charts.md
<table>
<tbody>
<tr>
<td>
</td>
<td>
<p><a href="https://syncfusion.atlassian.net/browse/WF-64189">https://syncfusion.atlassian.net/browse/WF-64189</a></p>
</td>
</tr>
<tr>
<td>
</td>
<td>
<p>Modify the UG content of Waterfall chart in Presentation</p>
</td>
</tr>
<tr>
<td>
</td>
<td>
<p>Modify the data points of the Waterfall chart to preserve Waterfall chart properly in Presentation document.</p>
</td>
</tr>
</tbody>
</table>
=> WF-64189-Modify the UG content of Waterfall chart in Presentation

File-Formats/PDF/PdfGrid (Recommended).md
Hi Sir, 
I have rectify the spelling error in PdfGrid.md file. Kindly review and merge this.  
Regards,
Sowmiya L
=> EJDOTNETCORE-3945 - Resolve the spelling error in PdfGrid.md - Hotfix

File-Formats-toc.html
Hi Sir, 
I have partitioned the "Working with Tables" into "PdfGrid" and "PdfLightTable". But unfortunately the TOC commit has been missed in the merged PR. So here I have raised this to add TOC for PDF Table. Kindly review and merge this. 
Regrads,
Sowmiya L
=> EJDOTNETCORE-3945 - Added the TOC for PDF Tables - Hotfix

File-Formats/DocIO/Working-with-Word-document.md
Added UG documentation to md fileformat to hide and remove backgrounds in Word document.
=> WF-45111-Add UG Documentation to DisplayBackgrounds property and remove existing background

File-Formats-toc.html, File-Formats/PDF/Working-with-Tables.md
Hi Sir, 
In TOC file, have missed to add the </li> tag in the end of sub topics "PdfGrid" and "PdfLightTable". Can you please review this and merge. 
Regards,
Sowmiya L
=> EJDOTNETCORE-3945 - Resolving the tag issues in TOC - Hotfix

File-Formats/DocIO/Working-with-Find-and-Replace.md, File-Formats/DocIO/Working-with-Tables.md
<table>
<tbody>
<tr>
<td>
</td>
<td>
<p><a href="https://syncfusion.atlassian.net/browse/WF-52737">https://syncfusion.atlassian.net/browse/WF-52737</a></p>
</td>
</tr>
<tr>
<td>
</td>
<td>
<p>How to insert a row with the same formatting in a Word document?</p>
</td>
</tr>
<tr>
<td>
</td>
<td>
<p>Added FAQ in UG pages to redirect for KB</p>
</td>
</tr>
</tbody>
</table>
=> WF-52737- How to insert a row with the same formatting in a Word document?

File-Formats/DocIO/word-to-image.md
<table>
<tbody>
<tr>
<td>
</td>
<td>
<p><a href="https://syncfusion.atlassian.net/browse/WF-64286">https://syncfusion.atlassian.net/browse/WF-64286</a></p>
</td>
</tr>
<tr>
<td>
</td>
<td>
<p>Update a UG documentation with Underline style and Strikethrough support</p>
</td>
</tr>
<tr>
<td>
</td>
<td>
<p>Remove underline styles details in unsupported elements in Word to PDF page.</p>
</td>
</tr>
</tbody>
</table>
=> WF-64286-Update a UG documentation with Underline style and Strikethrough support

File-Formats/DocIO/Working-with-Word-document.md
Kindly review the below changes for merging and let me know your feedback.
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-45111">https://syncfusion.atlassian.net/browse/WF-45111</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Add UG document about DisplayBackgrounds property and remove existing background.
</td>
</tr>
<tr>
<td>
Solution
</td>
<td>
Added code snippet in Working with Word document in all platforms. 
</td>
</tr>
<tr>
<td>
</td>
<td>
Not yet
</td>
</tr>
</table>
=> WF-45111-Added UG Documentation to DisplayBackgrounds property and remove existing background

File-Formats/DocIO/Working-with-Footnotes-and-endnotes.md
Added UG Documentation to Footnotes-and-Endnotes md fileformat for Modify Footnote and Endnote content.
=> WF-62406-Add UG Documentation to Modify Footnote and Endnote content

File-Formats/DocIO/Working-with-Find-and-Replace.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-51781">https://syncfusion.atlassian.net/browse/WF-51781</a><br/>
<a href="https://syncfusion.atlassian.net/browse/WF-64170">https://syncfusion.atlassian.net/browse/WF-64170</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Added more use cases of find and replace in UG documentation
</td>
</tr>
<tr>
<td>
Changes Done
</td>
<td>
Added UG documentation for 6 API's in find and replace functionality.<p/>
- Replace(Regex pattern, string replace);
- ReplaceSingleLine(Regex pattern, string replace);
- Find(Regex pattern);
- Replace(string given, TextSelection textSelection, bool caseSensitive, bool wholeWord, bool saveFormatting);
- …
=> WF-51781-Added more use cases of find and replace in UG documentation

File-Formats/Presentation/Presentation-to-PDF.md
<table>
<tbody>
<tr>
<td>
</td>
<td>
<p><a href="https://syncfusion.atlassian.net/browse/WF-63099">https://syncfusion.atlassian.net/browse/WF-63099</a></p>
</td>
</tr>
<tr>
<td>
</td>
<td>
<p>Update Presentation control UG documentation with tagged PDF code snippet</p>
</td>
</tr>
<tr>
<td>
</td>
<td>
<p>Add a code snippet in UG page to convert PowerPoint Presentation to PDF with structures tags.</p>
</td>
</tr>
</tbody>
</table>
=> WF-63099-Update Presentation control UG documentation with tagged PDF code snippet

File-Formats/XlsIO/Working-with-Data.md
=> WF-64214 - UG documentation for import HTML table with formula support - Development

File-Formats/DocIO/FAQ.md, File-Formats/DocIO/Getting-Started.md, File-Formats/DocIO/Silverlight.md, File-Formats/DocIO/Working-With-Content-Controls.md, File-Formats/DocIO/Working-with-Find-and-Replace.md, File-Formats/DocIO/html.md, File-Formats/DocIO/mail-merge/mail-merge-options.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-64352">https://syncfusion.atlassian.net/browse/WF-64352</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Modify backward slash with forward slash in file path.
</td>
</tr>
<tr>
<td>
Solution
</td>
<td>
Modified backward slash with forward slash in file path for DocIO.
</td>
</tr>
</table>
=> WF-64352-Modify backward slash with forward slash in file path for DocIO

File-Formats/DocIO/Working-with-Footnotes-and-endnotes.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-51785">https://syncfusion.atlassian.net/browse/WF-51785</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Add UG document for Setting Footnote and Endnote position.
</td>
</tr>
<tr>
<td>
Solution
</td>
<td>
Added code snippet in Footnotes and Endnote page in all platforms. 
- Set Footnote position
- Set Endnote position
</td>
</tr>
<tr>
<td>
</td>
<td>
Done
</td>
</tr>
</table>
=> WF-51785-Add UG documentation to Set Footnote and Endnote position

File-Formats/DocIO/Working-with-Footnotes-and-endnotes.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-62406">https://syncfusion.atlassian.net/browse/WF-62406</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Add UG document to Modify Footnote and Endnote content in a Word document.
</td>
</tr>
<tr>
<td>
Solution
</td>
<td>
Added code snippet in Footnotes and Endnote page in all platforms. 
- Modify Footnote content
- Modify Endnote content
</td>
</tr>
<tr>
<td>
</td>
<td>
Done
</td>
</tr>
</table>
=> WF-62406-Add UG documentation to Modify Footnote and Endnote content in a Word document

File-Formats/DocIO/Working-with-Table-Of-Contents.md
<table>
<tbody>
<tr>
<td>
</td>
<td>
<p><a href="https://syncfusion.atlassian.net/browse/Ejdotnetcore-4000">https://syncfusion.atlassian.net/browse/Ejdotnetcore-4000</a></p>
</td>
</tr>
<tr>
<td>
</td>
<td>
<p>How to customize the TOC entries style in Word document?</p>
</td>
</tr>
<tr>
<td>
</td>
<td>
<p>Added KB sample</p>
</td>
</tr>
</tbody>
</table>
=> Ejdotnetcore-4000-How to customize the TOC entries style in Word document

File-Formats/DocIO/Working-with-Find-and-Replace.md
<table>
<tbody>
<tr>
<td>
</td>
<td>
<p><a href="https://syncfusion.atlassian.net/browse/EJDOTNETCORE-4001">https://syncfusion.atlassian.net/browse/EJDOTNETCORE-4001</a></p>
<p><a href="https://syncfusion.atlassian.net/browse/WF-64148">https://syncfusion.atlassian.net/browse/WF-64148</a>
<p><a href="https://syncfusion.atlassian.net/browse/EJ2CORE-874">https://syncfusion.atlassian.net/browse/EJ2CORE-874</a></p>
</td>
</tr>
<tr>
<td>
</td>
<td>
<p>How to find and replace text inside table?</p>
<p>How to find and replace text in headers and footers of Word document?</p>
<p>How to find and replace placeholder with page break in Word document?</p>
</td>
</tr>
<tr>
<td> …
=> WF-64352-Add KB links in Find and Replace UG

File-Formats/PDF/Working-with-DigitalSignature.md
Hi @chinnumuniyappan,
Kindly review the UG documentation for LTV information and customizing revocation
The content review documentation is available in the UG documentation task, https://syncfusion.atlassian.net/browse/WF-62649
Regards,
Anantha Gokula Raman J
=> EJDOTNETCORE-3823 UG documentation for LTV information and revocation customization

File-Formats/DocIO/Working-with-Find-and-Replace.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-64150">https://syncfusion.atlassian.net/browse/WF-64150</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Add UG document for find next and replace with formatted text.
</td>
</tr>
<tr>
<td>
Solution
</td>
<td>
Added code snippet in Find and Replace platform. 
- Find and replace non-breaking spaces with regular spaces
</td>
</tr>
<tr>
<td>
</td>
<td>
Done
</td>
</tr>
</table>
=> WF-64150-Adding UG documentation to Find next and replace with formatted text

File-Formats/DocIO/Working-with-Find-and-Replace.md, File-Formats/DocIO/Working-with-Sections.md
<table>
<tbody>
<tr>
<td>
</td>
<td>
<p><a href="https://syncfusion.atlassian.net/browse/EJ2CORE-881">https://syncfusion.atlassian.net/browse/EJ2CORE-881</a></p>
<p><a href="https://syncfusion.atlassian.net/browse/EJ2CORE-877">https://syncfusion.atlassian.net/browse/EJ2CORE-877</a></p>
</td>
</tr>
<tr>
<td>
</td>
<td>
<p>How to change section break in Word document as page break??</p>
<p>How to find and replace line break in Word document as paragraph mark</p>
</td>
</tr>
<tr>
<td>
</td>
<td>
<p>Added FAQ in UG pages to redirect for KB</p>
</td>
</tr>
</tbody>
</table>
=> WF-64151-Added KB links in Find and Replace , working with Sections UG

File-Formats/DocIO/FAQ.md, File-Formats/DocIO/NuGet-Packages-Required.md, File-Formats/DocIO/word-to-image.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-64429">https://syncfusion.atlassian.net/browse/WF-64429</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
1. Modified word-to-Image.md file 
2. Modified FAQ
3. Modified NuGet-Packages-Required file
</td>
</tr>
</table>
=> WF-64429-Adding UG documentation to Add Information about Nugets for Word to Image in Linux

File-Formats/DocIO/FAQ.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-64429">https://syncfusion.atlassian.net/browse/WF-64429</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
1. Modified FAQ
</td>
</tr>
</table>
=> WF-64429-Adding UG documentation to Add Information about FAQfor Word to Image in Linux

File-Formats/PDF/Convert-HTML-To-PDF/advanced-installation.md, File-Formats/PDF/Convert-HTML-To-PDF/features.md, File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
WF-64344 Resolved image not showing issue in HTML to PDF UG
=> WF-64344 Resolved image not showing issue in HTML to PDF UG

File-Formats/XlsIO/Working-with-Excel-Worksheet.md
=> EJDOTNETCORE-4064 - Maximum Rows and Columns for CSV - HF

File-Formats/DocIO/Working-with-Find-and-Replace.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-64151">https://syncfusion.atlassian.net/browse/WF-64151</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Added more use cases of find and replace in UG documentation
</td>
</tr>
<tr>
<td>
Changes Done
</td>
<td>
Added UG documentation for 2 API's in find and replace functionality.<p/>
- FindNextSingleLine(TextBodyItem startBodyItem, Regex pattern);  
- Replace(string given, TextSelection textSelection, bool caseSensitive, bool wholeWord); 
</td>
</tr>
</table>
=> WF-64151-Add UG documentation for FindNextSingleLine and Replace API

File-Formats/XlsIO/Working-with-Cell-or-Range-Formatting.md, File-Formats/XlsIO/Working-with-Pictures.md
=> WF-44415-AlignPicture, WF-44402-UnwrapText

File-Formats/Presentation/create-read-edit-powerpoint-files-in-uwp.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-wpf.md
=> TEST-34253-Corrected the indention issues for WF controls in file format UG documentation

File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
WF-64268 Update more information about blink troubleshooting details
=> WF-64268 Update more information about blink troubleshooting details

File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
WF-64268 Update more information about blink troubleshooting details.
=> WF-64268 Update more information about blink troubleshooting details.

File-Formats/DocIO/FAQ.md, File-Formats/DocIO/NuGet-Packages-Required.md, File-Formats/DocIO/word-to-pdf.md, File-Formats/Presentation/FAQ.md, File-Formats/Presentation/Presentation-to-PDF.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-64328">https://syncfusion.atlassian.net/browse/WF-64328</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Update a UG documentation with latest SkiaSharp version details.
</td>
</tr>
<tr>
<td>
Solution
</td>
<td>
Added latest SkiaSharp version details in DocIO and Presentation pages.
</td>
</tr>
</table>
=> WF-64328-Update a UG documentation with latest SkiaSharp version details

File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
WF-64268 Blink troubleshooting changes updated
=> WF-64268 Blink troubleshooting changes updated

File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
WF-64268 Updated blink troubleshooting changes
=> WF-64268 Updated blink troubleshooting changes

File-Formats/PDF/Convert-HTML-To-PDF/azure.md
EJDOTNETCORE-4079 Add UG documentation for Azure and AWS for HTML to PDF
=> EJDOTNETCORE-4079 Add UG documentation for Azure and AWS for HTML to PDF

File-Formats/PDF/Working-with-OCR/Dot-NET-Core.md
Hi team,
I have added the UG documentation for performing OCR with AWS Textract.
Regards,
Karmegam
=> EJDOTNETCORE-4161 Add UG documentation for AWS Textract OCR and github sample

File-Formats/PDF/Working-with-OCR/Dot-NET-Core.md
Hi team,
I have moved the development changes for AWS textract UG documentation.
Regards,
Karmegam
=> EJDOTNETCORE-4161-Add UG documentation for AWS Textract OCR in hotfix

File-Formats/XlsIO/Chart-to-Image-Conversion.md
Please review and merge the change.
Regards,
Keerthi.
=> WF-64849 - Add in UG - Chart Sheets are not supported in Chart To Image Conversion -HF

File-Formats/PDF/Convert-HTML-To-PDF/azure.md, File-Formats/PDF/Convert-HTML-To-PDF/mac.md
Hi sir,
Mac image check in UG
Regards,
sameerkhan N
=> EJDOTNETCORE-4218-1 Mac image check in UG

File-Formats/PDF/Assemblies-Required.md, File-Formats/PDF/NuGet-Packages-Required.md
Hi All, 
I have updated the NuGet package required and assemblies required page for HTML to PDF topic. Please review the changes and merge.
Regards,
Sowmiya L
=> EJDOTNETCORE-4257 - Update HTML to PDF NuGet package required and assemblies required in UG - Hotfix

File-Formats/DocIO/word-to-markdown.md
<table>
<tbody>
<tr>
<td>Task Link</td>
<td>https://syncfusion.atlassian.net/browse/WF-63881</td>
</tr>
<tr>
<td>Description</td>
<td>Add UG document for&nbsp;Word to Markdown Conversion</td>
</tr>
<tr>
<td>Solution</td>
<td>Modified documentation to split SaveImage method</td>
</tr>
<tr>
<td>Content review confirmation</td>
<td>Yes</td>
</tr>
</tbody>
</table>
=> WF-63881-Add UG document for Word to Markdown Conversion

File-Formats/DocIO/Working-with-Table-Of-Contents.md
<tbody>
<tr>
<td style="width: 349.306px;">https://syncfusion.atlassian.net/browse/WF-64807</td>
</tr>
<tr>
<td style="width: 349.306px;">Add UG document to&nbsp; customize Table of contents</td>
</tr>
<tr>
<td style="width: 349.306px;">Added code snippet to customize table of contents</td>
</tr>
<tr>
<td style="width: 349.306px;">Not yet</td>
</tr>
</tbody>
</table>
=> WF-64807-Adding UG documentation to IncludeNewLineCharacters API

File-Formats/DocIO/Working-with-Table-Of-Contents.md
<tbody>
<tr>
<td style="width: 349.306px;">https://syncfusion.atlassian.net/browse/WF-64807</td>
</tr>
<tr>
<td style="width: 349.306px;">Add UG document to&nbsp; customize Table of contents</td>
</tr>
<tr>
<td style="width: 349.306px;">Resolved alignment issue in code snippet.</td>
</tr>
<tr>
</tr>
</tbody>
</table>
=> WF-64807-Add UG document to IncludeNewLineCharacters API

File-Formats-toc.html, File-Formats/Presentation/Working-with-find-and-replace.md
<html>
<body>
Task Link | https://syncfusion.atlassian.net/browse/WF-64957
-- | --
Description | Add UG document for Presentation find and replace
Solution | Added UG document for Presentation find and replace
Content review confirmation | No
</body>
</html>
=> WF-64957-Documentation-for-find-and-replace-in-Presentation

File-Formats/PDF/Convert-HTML-To-PDF/WPF.md, File-Formats/PDF/Convert-HTML-To-PDF/Windows-Forms.md, File-Formats/PDF/Convert-HTML-To-PDF/aspnet-mvc.md, File-Formats/PDF/Convert-HTML-To-PDF/aws.md, File-Formats/PDF/Convert-HTML-To-PDF/azure.md, File-Formats/PDF/Convert-HTML-To-PDF/blazor.md, File-Formats/PDF/Convert-HTML-To-PDF/docker.md, File-Formats/PDF/Convert-HTML-To-PDF/linux.md, File-Formats/PDF/Convert-HTML-To-PDF/mac.md, File-Formats/PDF/Convert-HTML-To-PDF/net-core.md
Hi All, 
I have resolved the code indentation issues in HTML to PDF UG page. Kindly review this and merge. 
Regards,
Sowmiya L
=> EJDOTNETCORE-4296 - Resolve the code indentation issues in HTML to PDF page - Hotfix 

File-Formats/PDF/Working-with-DigitalSignature.md
Hi All, 
I have added the below topic in digital signature UG documentation, 
- Remove existing digital signature from the PDF document 
- Author or Certify signature 
- Retrieve digital signature information from an existing PDF document 
- Resolved code indentation issues for all the topics in digital signature UG 
Regards,
Sowmiya L
=> EJDOTNETCORE-4293 - Add missing topics in digital signature topic - Hotfix 

File-Formats/PDF/Working-with-DigitalSignature.md
Hi All,
I have added below topics in UG
Add topic – Digitally sign a PDF using Windows Certificate Store
Add topic - Digitally sign a PDF document with long-term archive timestamps (LTA)
Content reviewed task link: https://syncfusion.atlassian.net/browse/WF-64971
Can you review and marge this PR
Regards,
Sameerkhan N
=> EJDOTNETCORE-4294 A Need to improvise PDF digital signature UG documentation page

File-Formats/PDF/Create-PDF-file-in-C-Sharp-VB-NET.md
Hi All, 
I have updated the below in HTML to PDF conversion topic. Kindly review this and merge. 
- HTML to PDF description 
- Installation details 
- Code snippet 
Regards,
Sowmiya L
=> EJDOTNETCORE-4316 - Revamp HTML to PDF content in Create-PDF-file-in-C-Sharp-VB-NET.md file - Hotfix 

File-Formats/DocIO/Create-Word-document-in-ASP-NET-Core.md, File-Formats/DocIO/Create-Word-document-in-ASP-NET-MVC.md, File-Formats/DocIO/Create-Word-document-in-ASP-NET.md, File-Formats/DocIO/Create-Word-document-in-Blazor.md, File-Formats/DocIO/Create-Word-document-in-Linux.md, File-Formats/DocIO/Create-Word-document-in-MAUI.md, File-Formats/DocIO/Create-Word-document-in-Mac.md, File-Formats/DocIO/Create-Word-document-in-UWP.md, File-Formats/DocIO/Create-Word-document-in-WPF.md, File-Formats/DocIO/Create-Word-document-in-WinUI.md, File-Formats/DocIO/Create-Word-document-in-Windows-Forms.md, File-Formats/DocIO/Create-Word-document-in-Xamarin.md, File-Formats/DocIO/word-to-pdf-linux-docker.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-asp-net-core-c-sharp.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-asp-net-mvc.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-asp-net-web-forms.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-blazor.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-linux.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-mac.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-maui.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-uwp.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-windows-forms.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-winui.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-wpf.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-xamarin.md
<tbody>
<tr>
<td style="width: 349.306px;">https://syncfusion.atlassian.net/browse/WF-64948</td>
</tr>
<tr>
<td style="width: 349.306px;">Resolve numbering issues in Getting started pages of DocIO</td>
</tr>
<tr>
<td style="width: 349.306px;">Resolved numbering issues in Getting started pages of DocIO</td>
</tr>
<tr>
</tr>
</tbody>
</table>
=> WF-64948-Resolve numbering issues in Getting started pages of DocIO and Presentation

File-Formats/Presentation/Getting-Started.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-asp-net-core-c-sharp.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-asp-net-mvc.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-asp-net-web-forms.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-blazor.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-linux.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-mac.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-maui.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-uwp.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-windows-forms.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-winui.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-wpf.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-xamarin.md
<tbody>
<tr>
<td style="width: 349.306px;">https://syncfusion.atlassian.net/browse/WF-64779</td>
</tr>
<tr>
<td style="width: 349.306px;">Resolve&nbsp;formatting issue in getting started pages of Presentation UG</td>
</tr>
<tr>
<td style="width: 349.306px;">Resolved formatting issue in getting started pages of Presentation UG</td>
</tr>
<tr>
</tr>
</tbody>
</table>
=> WF-64779-Fix the formatting issues in Getting started pages of Presentation UG

File-Formats/Presentation/Getting-Started.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-asp-net-core-c-sharp.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-asp-net-mvc.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-asp-net-web-forms.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-blazor.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-linux.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-mac.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-maui.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-uwp.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-windows-forms.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-winui.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-wpf.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-xamarin.md
Reverts syncfusion-content/fileformat-docs#701
=> WF-64779-Revert-Fix the formatting issues in Getting started pages of Presentation UG

File-Formats/DocIO/FAQ.md
<table>
<tr>
<td>
Task Link
</td>
<td>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Cleaning up FAQ md file
</td>
</tr>
</table>
=> WF-65032-Cleaning up FAQ md file

File-Formats/DocIO/FAQ.md, File-Formats/DocIO/rtf.md, File-Formats/DocIO/text.md, File-Formats/DocIO/word-file-formats.md, File-Formats/DocIO/word-to-pdf.md
<table>
<tr>
<td>
Task Link
</td>
<td>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
1. Cleaning up FAQ md file
2. Cleaning up Word-File-Formats md file
3. Cleaning up word to pdf md file
4. Cleaning up rtf file
5. Cleaning up text conversion md file
</td>
</tr>
</table>
=> WF-65032-Cleaning up FAQ md file, File formats md file, word to pdf md file, rtf md file, text conversion md file

File-Formats/DocIO/Accepting-or-Rejecting-Track-Changes.md, File-Formats/DocIO/Working-With-Content-Controls.md, File-Formats/DocIO/Working-with-Footnotes-and-endnotes.md, File-Formats/DocIO/Working-with-Macros.md, File-Formats/DocIO/Working-with-Security.md, File-Formats/DocIO/html.md, File-Formats/DocIO/word-to-odt.md
<table>
<tr>
<td>
Task Link
</td>
<td>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
1. Cleaning up HTML md file
2. Cleaning up Word-to-odt md file
3. Cleaning up accepting and rejecting track changes md file
4. Cleaning up macros file
5. Cleaning up working-with-content-controls md file
6. Cleaning up working-with-footnotes-and-endnotes md file
7. Cleaning up working-with-security md file
</td>
</tr>
</table>
=> WF-65032-Fixed the formatting issues in DocIO UG

File-Formats/Presentation/Working-with-Tables.md, File-Formats/Presentation/Working-with-images.md, File-Formats/Presentation/Working-with-list.md, File-Formats/Presentation/Working-with-paragraphs.md, File-Formats/Presentation/Working-with-shapes.md, File-Formats/Presentation/create-read-edit-master-slide-and-layout-slide-in-c-sharp.md
<tbody>
<tr>
<td style="width: 349.306px;">https://syncfusion.atlassian.net/browse/WF-64779</td>
</tr>
<tr>
<td style="width: 349.306px;">Resolved formatting issues in Getting started pages of DocIO</td>
</tr>
<tr>
<td style="width: 349.306px;">Resolve formatting issues in loading and saving, Working with presentation, Slides, Paragraph, Lists, images and table pages of DocIO</td>
</tr>
<tr>
</tr>
</tbody>
</table>
=> WF-64779-Fix the formatting issues in Presentation UG

File-Formats/PDF/Convert-HTML-To-PDF/Blink.md, File-Formats/PDF/Create-PDF-file-in-C-Sharp-VB-NET.md
Hi All, 
Resolved the file format UG issues
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/SAMEER~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/SAMEER~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/SAMEER~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">
<style>
</style>
</head>
<body lang=EN-US link=blue …
=> EJDOTNETCORE-4316-1 File format UG issue resolved.

File-Formats/DocIO/Word-document/Iterating-Word-document-elements.md, File-Formats/DocIO/Word-document/Merging-Word-documents.md, File-Formats/DocIO/Word-document/Print-Word-documents.md, File-Formats/DocIO/Word-document/Split-Word-documents.md, File-Formats/DocIO/Working-with-Bookmarks.md, File-Formats/DocIO/Working-with-Fields.md, File-Formats/DocIO/Working-with-Paragraph.md, File-Formats/DocIO/Working-with-Sections.md, File-Formats/DocIO/Working-with-Shapes.md, File-Formats/DocIO/Working-with-Tables.md, File-Formats/DocIO/Working-with-Word-document.md
<table>
<tr>
<td>
Task Link
</td>
<td>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
1. Cleaning up Shapes md file
2. Cleaning up Fields md file
3. Cleaning up Bookmarks md file
4. Cleaning up Tables md file
5. Cleaning up Paragraphs md file
6. Cleaning up Sections md file
7. Cleaning up Word Document md file
8. Cleaning up Iterating Word document elements md file
9. Cleaning up Merging Word documents md file
10. Cleaning up Print Word documents md file
11. Cleaning up Split Word documents md file
</td>
</tr>
</table>
=> WF-65032-Fixed Formatting issues in UG DocIO

File-Formats/DocIO/Create-Word-document-in-Blazor.md, File-Formats/DocIO/Create-Word-document-in-UWP.md, File-Formats/DocIO/Create-Word-document-in-WinUI.md, File-Formats/DocIO/Create-Word-document-in-Xamarin.md, File-Formats/DocIO/Getting-Started.md, File-Formats/DocIO/Loading-and-Saving-document.md
<table>
<tr>
<td>
Task Link
</td>
<td>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
1. Cleaning up UG md files
</tr>
</table>
=> WF-65032-Fixed Formatting issues in DocIO UG

File-Formats/Presentation/NuGet-Packages-Required.md
<html>
<body>
<p dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Kindly review the below merge request and let me know …
=> WF-64677-Remove-SkiaSharpHelper-details-in-NuGet-required-UG-page

File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
Hi All, 
Cureent version updated in HTML to PDF troubleshoot Newtonsoft.json Nuget 
Regards,
Sameerkhan N
=> WF-65006 Version updated in newtonsoft.json nuget package

File-Formats/Presentation/NuGet-Packages-Required.md
<html>
<body>
<p dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Kindly review the below merge request and let me know …
=> WF-64677-Remove-SkiaSharpHelper-details-in-NuGet-required-UG-page-Latest

File-Formats/DocIO/Getting-Started.md, File-Formats/Presentation/Getting-Started.md, File-Formats/Presentation/Loading-and-Saving-the-Presentation.md, File-Formats/Presentation/Working-with-Charts.md, File-Formats/Presentation/Working-with-OLE-Objects.md, File-Formats/Presentation/Working-with-PowerPoint-presentation.md, File-Formats/Presentation/Working-with-Slide.md, File-Formats/Presentation/Working-with-find-and-replace.md, File-Formats/Presentation/create-edit-connectors-in-powerpoint-slides-cs-vb-net.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-asp-net-core-c-sharp.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-asp-net-mvc.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-asp-net-web-forms.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-blazor.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-linux.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-mac.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-maui.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-uwp.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-windows-forms.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-winui.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-wpf.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-xamarin.md
<tbody>
<tr>
<td style="width: 349.306px;">https://syncfusion.atlassian.net/browse/WF-65091</td>
</tr>
<tr>
<td style="width: 349.306px;">Resolved formatting issues in Presentation UG</td>
</tr>
<tr>
<td style="width: 349.306px;">Resolve formatting issues in Getting started, Loading-and-Saving-the-Presentation, Working-with-PowerPoint-presentation, Working-with-Slide, ASP.Net Core, ASP.Net MVC, ASP.Net, Blazor, Xamarin, .NET MAUI, UWP, WPF, Windows Form, WinUI, Linux, Mac, Working-with-find-and-replace, Working-with-Charts and create-edit-connectors-in-powerpoint-slides-cs-vb-net</td>
</tr>
<tr>
<td style="width: 156px;">Content …
=> WF-65091-Fix the formatting issues in Presentation UG

File-Formats/DocIO/Create-Word-document-in-ASP-NET-Core.md, File-Formats/DocIO/Create-Word-document-in-ASP-NET-MVC.md, File-Formats/DocIO/Create-Word-document-in-ASP-NET.md, File-Formats/DocIO/Create-Word-document-in-Blazor.md, File-Formats/DocIO/Create-Word-document-in-Linux.md, File-Formats/DocIO/Create-Word-document-in-MAUI.md, File-Formats/DocIO/Create-Word-document-in-Mac.md, File-Formats/DocIO/Create-Word-document-in-UWP.md, File-Formats/DocIO/Create-Word-document-in-WPF.md, File-Formats/DocIO/Create-Word-document-in-WinUI.md, File-Formats/DocIO/Create-Word-document-in-Windows-Forms.md, File-Formats/DocIO/Create-Word-document-in-Xamarin.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-blazor.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-linux.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-mac.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-maui.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-uwp.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-winui.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-wpf.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-xamarin.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-65124">https://syncfusion.atlassian.net/browse/WF-65124</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Fix formatting issues in DocIO and Presentation pages.
</td>
</tr>
<tr>
<td>
Solution
</td>
<td>
Fixed code snippet alignment in getting started pages.
</td>
</tr>
</table>
=> WF-65124-Fixed code snippet alignment in getting started pages

File-Formats/PDF/Convert-HTML-To-PDF/advanced-installation.md, File-Formats/PDF/Convert-HTML-To-PDF/blazor.md, File-Formats/PDF/Convert-HTML-To-PDF/mac.md, File-Formats/PDF/Converting-HTML-to-PDF.md, File-Formats/PDF/Working-with-Annotations.md, File-Formats/PDF/Working-with-Bookmarks.md, File-Formats/PDF/Working-with-Brushes.md, File-Formats/PDF/Working-with-Document.md, File-Formats/PDF/Working-with-Headers-and-Footers.md, File-Formats/PDF/Working-with-Image-Extraction.md, File-Formats/PDF/Working-with-Images.md, File-Formats/PDF/Working-with-Named-Destination.md, File-Formats/PDF/Working-with-Pages.md, File-Formats/PDF/Working-with-Shapes.md, File-Formats/PDF/Working-with-Text-Extraction.md, File-Formats/PDF/Working-with-Text.md
Hi All,
Added API references and remove unwanted code space in PDF UG documentation.
Regards,
Sameerkhan N
=> EJDOTNETCORE-4344 Updated link and unwanted code space

File-Formats/PDF/Merge-Documents.md, File-Formats/PDF/Working-with-Document-Conversions.md, File-Formats/PDF/Working-with-Flow-Layout.md, File-Formats/PDF/Working-with-HyperLinks.md, File-Formats/PDF/Working-with-PDF-Templates.md, File-Formats/PDF/Working-with-XFA.MD, File-Formats/PDF/Working-with-forms.md
Hi Sir,
Added API link and remove unwanted code space in PDF UG documentation.
Regards,
Jeyalakshmi T
=> EJDOTNETCORE-4349 Need to add API references in PDF UG documentation

File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md, File-Formats/PDF/Working-with-DigitalSignature.md
Hi All,
updated UG documentation in troubleshooting section.
Newtonsoft.Json  Checked the current version
Regards,
Sameerkhan N
=> WF-65006-1 Updated the UG documentation for Html To PDF conversion troubleshooting section

File-Formats/DocIO/Accepting-or-Rejecting-Track-Changes.md, File-Formats/DocIO/FAQ.md, File-Formats/DocIO/Loading-and-Saving-document.md, File-Formats/DocIO/Word-document/Iterating-Word-document-elements.md, File-Formats/DocIO/Working-With-Content-Controls.md, File-Formats/DocIO/Working-with-Charts.md, File-Formats/DocIO/Working-with-Mathematical-Equation.md, File-Formats/DocIO/Working-with-Paragraph.md, File-Formats/DocIO/Working-with-Table-Of-Contents.md, File-Formats/DocIO/Working-with-Word-document.md, File-Formats/DocIO/convert-word-document-to-markdown-in-csharp.md, File-Formats/DocIO/mail-merge/mail-merge-options.md, File-Formats/DocIO/word-to-pdf.md, File-Formats/Presentation/Presentation-to-PDF.md, File-Formats/Presentation/create-read-edit-master-slide-and-layout-slide-in-c-sharp.md
<tbody>
<tr>
<td style="width: 349.306px;">https://syncfusion.atlassian.net/browse/WF-65091</td>
</tr>
<tr>
<td style="width: 349.306px;">Resolved formatting issues in Presentation UG</td>
</tr>
<tr>
<td style="width: 349.306px;">Resolve formatting and hyperlink issues in mail-merge-options, Iterating-Word-document-elements, Accepting-or-Rejecting-Track-Changes, FAQ, Loading-and-Saving-document, word-to-pdf, Working-with-Charts, Working-With-Content-Controls, Working-with-Mathematical-Equation, Working-with-Paragraph, Working-with-Table-Of-Contents, Working-with-Word-document, …
=> WF-65091-Address formatting issues in DocIO and Presentation

File-Formats/XlsIO/Create-read-edit-excel-files-in-blazor-c-sharp.md
=> WF-65128 - Update XlsIO UG to read Excel file in Blazor ClientSide Application

File-Formats/Presentation/Getting-Started.md, File-Formats/Presentation/Loading-and-Saving-the-Presentation.md, File-Formats/Presentation/Working-with-Charts.md, File-Formats/Presentation/Working-with-PowerPoint-presentation.md, File-Formats/Presentation/Working-with-Slide.md, File-Formats/Presentation/Working-with-Tables.md, File-Formats/Presentation/Working-with-find-and-replace.md, File-Formats/Presentation/Working-with-images.md, File-Formats/Presentation/Working-with-list.md, File-Formats/Presentation/Working-with-paragraphs.md, File-Formats/Presentation/Working-with-shapes.md, File-Formats/Presentation/create-read-edit-master-slide-and-layout-slide-in-c-sharp.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-asp-net-core-c-sharp.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-asp-net-mvc.md
<tbody>
<tr>
<td style="width: 349.306px;">https://syncfusion.atlassian.net/browse/WF-65143</td>
</tr>
<tr>
<td style="width: 349.306px;">Resolved formatting issues in Presentation UG</td>
</tr>
<tr>
<td style="width: 349.306px;">Add GitHub sample links to - create-read-edit-master-slide-and-layout-slide-in-c-sharp, create-read-edit-powerpoint-files-in-asp-net-core-c-sharp, create-read-edit-powerpoint-files-in-asp-net-mvc, Getting-Started, Working-with-Charts, Working-with-find-and-replace, Working-with-images, Working-with-list, Working-with-paragraphs, Working-with-PowerPoint-presentation, Working-with-shapes, Working-with-Slide, …
=> WF-65143-Add GitHub sample links in Presentation UG

File-Formats/XlsIO/Create-read-edit-excel-files-in-blazor-c-sharp.md, File-Formats/XlsIO/Supported-Features-by-Platforms.md, File-Formats/XlsIO/Worksheet-to-Image-Conversion.md
=> WF-65168 - Worksheet to Image conversion in Blazor WASM Application - Hotfix

File-Formats/PDF/Working-with-OCR/Features.md
Hi All, 
I have resolved the CI failure in PDF UG documentation. Kindly review this and merge. 
Regards,
Sowmiya L
=> EJDOTNETCORE-4381 - Resolved the CI failures in PDF UG documentation - Hotfix

File-Formats-toc.html, File-Formats/PDF/Working-with-OCR/Features.md
Hi All, 
I have resolved the conflicts between master and latest hotfix branch. Kindly review this and merge. 
Regards,
Sowmiya L
=> EJDOTNETCORE-4381 - Resolve conflicts in master branch as like hotfix - Master 

File-Formats/PDF/Working-with-OCR/Features.md
Hi All, 
I have resolved the CI failure in live staging. Kindly review this and merge. 
Regards,
Sowmiya L
=> EJDOTNETCORE-4381 - Resolve the issue in CI failure - Hotfix

File-Formats/XlsIO/Create-read-edit-excel-files-in-blazor-c-sharp.md, File-Formats/XlsIO/Excel-to-PDF-Conversion.md, File-Formats/XlsIO/Supported-Features-by-Platforms.md
=> WF-65185-ExcelToPDFWASM-HF

File-Formats/DocIO/word-to-pdf.md
<tbody>
<tr>
<td style="width: 349.306px;">https://syncfusion.atlassian.net/browse/WF-65091</td>
</tr>
<tr>
<td style="width: 349.306px;">Resolved formatting issues in DocIO UG</td>
</tr>
<tr>
<td style="width: 349.306px;">Resolve formatting in word-to-pdf</td>
</tr>
<tr>
</tr>
</tbody>
</table>
[WF-65091]: https://syncfusion.atlassian.net/browse/WF-65091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WF-65091-Fix formatting issue

File-Formats/PDF/Convert-HTML-To-PDF/features.md, File-Formats/PDF/Open-and-Save-PDF-file-in-C-Sharp-VB-NET.md, File-Formats/PDF/Working-with-Annotations.md, File-Formats/PDF/Working-with-Images.md, File-Formats/PDF/Working-with-Named-Destination.md, File-Formats/PDF/Working-with-Pages.md, File-Formats/PDF/Working-with-Security.md
Hi Sir,
Added API link and removed unwanted code space in features md file and updated issue changes
Regards,
Sameerkhan N
=> EJDOTNETCORE-4344-1 Added API link and removed unwanted code space in features md file and updated the issue changes

File-Formats/Presentation/Getting-Started.md, File-Formats/Presentation/Presentation-to-PDF.md
<tbody>
<tr>
<td style="width: 349.306px;">https://syncfusion.atlassian.net/browse/WF-65219</td>
</tr>
<tr>
<td style="width: 349.306px;">Correcting namespace in Presentation UG</td>
</tr>
<tr>
<td style="width: 349.306px;">Added namespaces to the following md files-Getting-Started, word-to-pdf</td>
</tr>
<tr>
</tr>
</tbody>
</table>
[WF-65091]: https://syncfusion.atlassian.net/browse/WF-65091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WF-65219-Correct namespace in Presentation UG

File-Formats/PDF/Converting-HTML-to-PDF-in-Windows-Forms.md
Hi All, 
I have updated the file Converting-HTML-to-PDF-in-Windows-Forms.md in PDF UG documentation by adding the below, 
- Content 
- Screenshot 
- Sample 
Regards,
Sowmiya L
=> EJDOTNETCORE-4405 - Update Converting-HTML-to-PDF-in-Windows-Forms.md file - Hotfix

File-Formats/XlsIO/Supported-Features-by-Platforms.md
=> WF-65185-ConversionWASMXlsIO-HF

File-Formats/XlsIO/Loading-and-Saving-Workbook.md, File-Formats/XlsIO/Working-with-Excel-Worksheet.md, File-Formats/XlsIO/create-excel-file-csharp-vbnet.md
Hi @Mohan2401 , 
Please review and merge the API reference changes.
**Topics:**
1. Create Excel in C# and VB.NET (Getting Started)
2. Loading and Saving Workbook
3. Working with Excel Worksheet
Regards,
Keerthi.
=> WF-65186-APIReferencesXlsIO-HF

File-Formats/XlsIO/Working-with-Cell-or-Range-Formatting.md, File-Formats/XlsIO/Worksheet-Cells-Manipulation.md, File-Formats/XlsIO/Worksheet-Rows-and-Columns-Manipulation.md
Please review and merge the API reference changes.
**Topics:**
1. Working with Cell or Range Formatting
2. Working with Cell Manipulation
3. Working with Rows and Columns Manipulation
Regards,
Keerthi.
=> WF-65186-APIReferencesXlsIO-HF - PR2

File-Formats/XlsIO/Working-with-Charts.md, File-Formats/XlsIO/Working-with-Conditional-Formatting.md, File-Formats/XlsIO/Working-with-Data-Validation.md, File-Formats/XlsIO/Working-with-Data.md, File-Formats/XlsIO/Working-with-Excel-Tables.md, File-Formats/XlsIO/Working-with-Formulas.md, File-Formats/XlsIO/Working-with-Pictures.md, File-Formats/XlsIO/Working-with-Template-Markers.md
Please review and merge the API reference changes.
**Topics:**
1. Working with Data 
2. Working with Formulas
3. Working with Conditional Formatting
4. Working with Data Validation
5. Working with Charts
6. Working with Template Markers
7. Working with Tables
8. Working with Pictures
Regards,
Keerthi.
=> WF-65186-APIReferencesXlsIO-HF - PR3

File-Formats/PDF/Working-with-Document-Conversions.md
Hi All, 
I have updated the below in document conversion topic. Kindly review and merge this. 
- FT link 
- code example 
- UG documentation link 
Regards,
Sowmiya L
=> WF-65311 - Update HTML to PDF in document conversion topic - Hotfix

File-Formats/DocIO/Working-with-Charts.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-65263">https://syncfusion.atlassian.net/browse/WF-65263</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Add KB Chart Links to UG
</td>
</tr>
<tr>
<td>
Solution
</td>
<td>
Added KB Charts Links to UG
</td>
</tr>
<tr>
<td>
</td>
<td>
Done
</td>
</tr>
</table>
=> WF-65263-Modifying link

File-Formats/PDF/PdfGrid.md, File-Formats/PDF/PdfLightTable.md, File-Formats/PDF/Working-with-Compression.md, File-Formats/PDF/Working-with-OCR/Troubleshooting.md, File-Formats/PDF/Working-with-XFA.MD, File-Formats/PDF/Working-with-ZUGFeRD-invoice.md
Hi Sir, 
<html>
<body>
<figure class="table">
Trouble shooting OCR | Resolved table issue.
-- | --
PDFGrid.md | Resolved image View Issues.
PDFLightTable.md | Resolved image View Issues.
Working with XFA.md | Changed Link URL to Name URL.
Working with compresssion.md | Resolved link isssues.
Working with ZUGFeRD invoice.MD | Resolved image View Issues.
</figure>
</body>
</html>
Regards,
Sameerkhan N
=> EJDOTNETCORE-4399-1 Resolved the UG changes view issue in PDF.

File-Formats/XlsIO/Create-read-edit-excel-files-in-blazor-c-sharp.md
Kindly review and merge the sample redirection changes.
Regards,
Keerthi.
=> WF-65185 - Blazor WASM Samples Redirection for XlsIO - HF

File-Formats/DocIO/Create-Word-document-in-Blazor.md, File-Formats/DocIO/Supported-and-Unsupported-Features.md, File-Formats/DocIO/word-to-image.md, File-Formats/DocIO/word-to-pdf.md, File-Formats/Presentation/Presentation-to-PDF.md, File-Formats/Presentation/Presentation-to-image.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-65375">https://syncfusion.atlassian.net/browse/WF-65375</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Add Video and KB links in UG
</td>
</tr>
<tr>
<td>
Solution
</td>
<td>
Add Video and KB links in UG
</td>
</tr>
<tr>
<td>
</td>
<td>
Done
</td>
</tr>
</table>
=> WF-65263-Add video and KB links

File-Formats/DocIO/mail-merge/mail-merge-for-group.md, File-Formats/DocIO/mail-merge/mail-merge-for-nested-groups.md, File-Formats/DocIO/mail-merge/simple-mail-merge.md, File-Formats/DocIO/working-with-mail-merge.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-52318">https://syncfusion.atlassian.net/browse/WF-52318</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Added Execute,ExecuteGroup and ExecuteNestedGroup overloads to mail merge pages in UG.
</td>
</tr>
<tr>
<td>
Solution
</td>
<td>
Added mail merge overload method Links to UG
</td>
</tr>
<tr>
<td>
</td>
<td>
Pending
</td>
</tr>
</table>
=> WF-64420 Adding mail merge github links to UG

File-Formats/DocIO/mail-merge/mail-merge-for-group.md, File-Formats/DocIO/mail-merge/mail-merge-for-nested-groups.md, File-Formats/DocIO/mail-merge/simple-mail-merge.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-52318">https://syncfusion.atlassian.net/browse/WF-52318</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Added Execute,ExecuteGroup and ExecuteNestedGroup overloads to mail merge pages in UG.
</td>
</tr>
<tr>
<td>
Solution
</td>
<td>
Added mail merge overload method Links to UG
</td>
</tr>
<tr>
<td>
</td>
<td>
Pending
</td>
</tr>
</table>
=> WF-52318-removed unwanted codes

File-Formats/DocIO/Create-Word-document-in-Blazor.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-65375">https://syncfusion.atlassian.net/browse/WF-65375</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Add Video link in UG
</td>
</tr>
<tr>
<td>
Solution
</td>
<td>
Add Video link in UG
</td>
</tr>
<tr>
<td>
</td>
<td>
Done
</td>
</tr>
</table>
=> WF-65375-Video link

File-Formats-toc.html, File-Formats/XlsIO/FAQ.md, File-Formats/XlsIO/faqs/how-to-avoid-header-row-while-sorting-Excel-data.md, File-Formats/XlsIO/faqs/how-to-edit-existing-external-workbook-reference-link.md, File-Formats/XlsIO/faqs/how-to-edit-external-workbook-reference-link.md
**Tasks:** 
1. https://syncfusion.atlassian.net/browse/WF-65400 
2. https://syncfusion.atlassian.net/browse/WF-65401 
Regards,
Keerthi.
=> WF-65400-How to avoid header row while sorting a data range - WF-65401-How to edit existing external workbook reference link using Syncfusion XlsIO

File-Formats/DocIO/faqs/migrate-from-net-framework-to-net-core.md, File-Formats/Presentation/faqs/migrate-from-net-framework-to-net-core.md
Resolve presentation live issue
=> WF-65451-Migrate from .NET Framework to .NET core for DocIO and presentation 

File-Formats/PDF/Working-with-Images.md
Hi All, 
I have added the code example to replace images in an existing PDF document in ASP.NET Core. Kindly review this and merge.
Regards,
Sowmiya L
=> EJDOTNETCORE-4522 - Add .NET Core example for replacing images in an existing PDF document - Hotfix

File-Formats/DocIO/Working-with-Paragraph.md, File-Formats/DocIO/html.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-65424">https://syncfusion.atlassian.net/browse/WF-65424</a>
<a href="https://syncfusion.atlassian.net/browse/WF-62411">https://syncfusion.atlassian.net/browse/WF-62411</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
1. Add information about HTML export option
2. Apply paragraph formatting
</td>
</tr>
<tr>
<td>
Solution
</td>
<td>
1. Add information about HTML export option
2. Apply paragraph formatting
</td>
</tr>
<tr>
<td>
</td>
<td>
Done
</td>
</tr>
</table>
=> WF-65375-Add information about HTML export option and Apply paragraph formatting

File-Formats/XlsIO/Security.md
I have added encryption details for XlsIO.
=> WF-65433-Add-Encryption-details

File-Formats-toc.html, File-Formats/XlsIO/FAQ.md, File-Formats/XlsIO/faqs/how-to-set-error-bars-in-chart.md
I have added error bars in FAQ section.
=> WF-65433-Add-Error-bar-details

File-Formats/DocIO/faqs/migrate-from-net-framework-to-net-core.md, File-Formats/Presentation/faqs/migrate-from-net-framework-to-net-core.md
Resolve DocIO and presentation live issue
Parent PR : https://github.com/syncfusion-content/fileformat-docs/pull/863
=> WF-65451-Migrate from .NET Framework to .NET core for DocIO and presentation

File-Formats/DocIO/Document-Object-Model-representation.md, File-Formats/PDF/Working-with-OCR/Dot-NET-Framework.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-asp-net-core-c-sharp.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-asp-net-mvc.md, File-Formats/XlsIO/create-excel-file-csharp-vbnet.md
Please review image alt text changes for File Format.
Regards,
Sharly A.
=> SEO-2971 - File Format changed http to https

File-Formats/DocIO/Create-Word-document-in-ASP-NET-Core.md, File-Formats/DocIO/Create-Word-document-in-ASP-NET-MVC.md, File-Formats/DocIO/Create-Word-document-in-ASP-NET.md, File-Formats/DocIO/Create-Word-document-in-Blazor.md, File-Formats/DocIO/Create-Word-document-in-Linux.md, File-Formats/DocIO/Create-Word-document-in-MAUI.md, File-Formats/DocIO/Create-Word-document-in-Mac.md, File-Formats/DocIO/Create-Word-document-in-UWP.md, File-Formats/DocIO/Create-Word-document-in-WPF.md, File-Formats/DocIO/Create-Word-document-in-WinUI.md, File-Formats/DocIO/Create-Word-document-in-Windows-Forms.md, File-Formats/DocIO/Create-Word-document-in-Xamarin.md, File-Formats/DocIO/word-to-pdf-linux-docker.md, File-Formats/PDF/Working-with-OCR/Dot-NET-Framework.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-asp-net-core-c-sharp.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-asp-net-mvc.md, File-Formats/XlsIO/Create-read-edit-excel-files-in-asp-net-core-c-sharp.md, File-Formats/XlsIO/create-excel-file-csharp-vbnet.md, File-Formats/XlsIO/create-read-edit-excel-files-in-asp-net-mvc-c-sharp.md
Please review the changes in file format.
Regards,
Sharly A.
=> SEO-3267 - File Format Changes permanent redirect

File-Formats/PDF/Supported-and-Unsupported-Features.md
Hi Sir,
Updated the details for the support of blazor in the following features in UG
Please review and merge this
Regards,
Jeyalakshmi T
=> EJDOTNETCORE-4461 Need to update the details for the support of blazor in the following features in UG

File-Formats/PDF/Working-with-OCR/Working-with-OCR.md
Hi All, 
I have updated the NuGet package required section in PDF OCR UG documentation. Kindly review this and merge. 
Regards,
Sowmiya L
=> EJDOTNETCORE-4579 - Update PDF OCR NuGet package - Hotfix

File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
Updated UG documentation for HTMLToPDF troubleshooting section
=> WF-65555 Update UG documentation for HTMLToPDF troubleshooting section

File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
Updated UG documentation for HTMLToPDF troubleshooting section
=> WF-65564 Update UG documentation for HTMLToPDF troubleshooting section

File-Formats/PDF/Working-with-OCR/Troubleshooting.md
Hi All, 
I have added the best and fast tessdata details in troubleshooting OCR UG documentation. Kindly review this and merge. 
Regards,
Sowmiya L
=> WF-65512 - Add best and fast tessdata in OCR UG documentation - Hotfix

File-Formats/DocIO/convert-word-document-to-markdown-in-csharp.md
Updated the headings of Word to Markdonw UG
=> WF-65244-Word to Markdown_UG

File-Formats/PDF/Working-with-OCR/Dot-NET-Framework.md
Please review the changes for file format pdf.
Regards,
Sharly A.
=> SEO-3226 - File Format PDF

File-Formats/PDF/Create-PDF-document-in-Blazor.md, File-Formats/PDF/Working-with-DigitalSignature.md
Hi Sir,
Added video links in appropriate PDF UG. Please review and merge this 
Regards,
Jeyalakshmi T
=> EJDOTNETCORE-4548 Add video links in appropriate PDF UG

File-Formats-toc.html
Hi All, 
I have updated the TOC file. Please review this and merge. 
Regards,
Sowmiya L
=> EJDOTNETCORE-4520 -Update TOC - Hotfix

File-Formats/NuGet-Packages.md, File-Formats/PDF/Working-with-Colorspace.md
Worked on bing report issues, so merge these changes
Regards,
Gowthaman
=> SEO-3261-bing-report-issues

File-Formats-toc.html
Hi All, 
I have updated the TOC file. Kindly review this and let me know your feedback for the same. 
Regards,
Sowmiya L
=> EJDOTNETCORE-4520 - Update TOC file - Hotfix

File-Formats/DocIO/Working-with-Tables.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-65182">https://syncfusion.atlassian.net/browse/WF-65182</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Add UG document for apply base style to table styles using BuilinTableStyle
</td>
</tr>
<td>
</td>
<td>
Not yet
</td>
</tr>
</table>
=> WF-65182-Apply base style to table style UG documentation

File-Formats/PDF/FAQs/migrate-from-net-framework-to-net-core.md, File-Formats/PDF/Overview.md
Hi All, 
I have updated the below changes in migrating .NET Framework to .NET Core MD file. Kindly review this and merge this. 
Regards,
Sowmiya L
=> EJDOTNETCORE-4520 - Update description and add proper link in PDF migration from .NET Framework to .NET Core - Hotfix

File-Formats/Presentation/Presentation-to-PDF.md, File-Formats/XlsIO/Working-with-Pivot-Tables.md
Worked on SEMrush issues, so merge these changes
Regards,
Gowthaman
=> SEO-3356-semrush-report-issues

File-Formats-toc.html
Hi All,
I have resolved the file path issue by adding the title under list tag without anchor tag. Kindly review this and merge. 
Regards,
Sowmiya L
=> EJDOTNETCORE-4520 - Resolved the file path issue - development

File-Formats-toc.html, File-Formats/PDF/Converting-images-to-PDF.md
Hi All, 
I have added the new .md file for converting images to PDF and update the TOC file. Kindly review this and merge. 
Regards,
Sowmiya L
=> EJDOTNETCORE-4658 - Add new MD file for image to PDF - Hotfix

File-Formats-toc.html, File-Formats/PDF/Converting-XPS-to-PDF.md
Hi All,
Added Converting XPS to PDF md file in UG.
Regards,
Sameerkhan N
=> EJDOTNETCORE-4659 Added converting XPS to PDF md file.

File-Formats/DocIO/Working-with-Charts.md, File-Formats/DocIO/Working-with-Fields.md, File-Formats/DocIO/Working-with-Paragraph.md, File-Formats/DocIO/Working-with-Sections.md, File-Formats/DocIO/html.md
<tbody>
<tr>
<td style="width: 349.306px;">https://syncfusion.atlassian.net/browse/WF-59844</td>
</tr>
<tr>
<td style="width: 349.306px;">Added KB links to DocIO UG pages </td>
</tr>
<tr>
<td style="width: 349.306px;">Add KB links to Paragraphs, Sections, Fields, Loading and Saving word document, Working with Charts and html</td>
</tr>
<tr>
<td style="width: 349.306px;">Pending</td>
</tr>
</tbody>
</table>
=> WF-59844-Added KB links to UG pages

File-Formats/DocIO/Assemblies-Required.md, File-Formats/DocIO/NuGet-Packages-Required.md, File-Formats/PDF/Assemblies-Required.md, File-Formats/PDF/Convert-HTML-To-PDF/Blink.md, File-Formats/PDF/Convert-HTML-To-PDF/IE.md, File-Formats/PDF/Convert-HTML-To-PDF/WebKit.md, File-Formats/PDF/NuGet-Packages-Required.md, File-Formats/PDF/Working-with-Document-Conversions.md, File-Formats/PDF/Working-with-OCR/Working-with-OCR.md, File-Formats/PDF/Working-with-Text.md, File-Formats/Presentation/Assemblies-Required.md, File-Formats/Presentation/NuGet-Packages-Required.md, File-Formats/XlsIO/Assemblies-Required.md, File-Formats/XlsIO/NuGet-Packages-Required.md
Have changed File Format redirect links, please review.
Regards,
Yvone.
=> SEO-3297 File Format Redirect

File-Formats/PDF/Working-with-action.md
Hi All, 
I have added the code example for launch action in ASP.NET Core platform. Please review the changes and merge. 
Regards,
Sowmiya L
=> EJDOTNETCORE-3866 - Add code example for launch action in ASP.NET Core platform - Hotfix

File-Formats/PDF/FAQs/migrate-from-net-framework-to-net-core.md, File-Formats/PDF/Working-with-Document-Conversions.md
Hi All, 
I have added the code example for converting SVG to PDF document. Kindly review this and merge. 
Regards,
Sowmiya L
=> EJDOTNETCORE-4589 - Add code example for converting SVG to PDF - Hotfix

File-Formats/Presentation/Working-with-Tables.md, File-Formats/Presentation/Working-with-sections.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-65269">https://syncfusion.atlassian.net/browse/WF-65269</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Modifying code snippets
</td>
</tr>
<td>
</td>
<td>
Done
</td>
</tr>
</table>
=> WF-65269-Modifying code snippet of inserting section and merging table cells

File-Formats/DocIO/Working-with-Tables.md, File-Formats/DocIO/convert-markdown-to-word-document-in-csharp.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-65244">https://syncfusion.atlassian.net/browse/WF-65244</a>
<a href="https://syncfusion.atlassian.net/browse/WF-65182">https://syncfusion.atlassian.net/browse/WF-65182</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Address Markdown to Word and Apply Base style feedbacks
</td>
</tr>
<td>
</td>
<td>
Done
</td>
</tr>
</table>
=> WF-65244-Address Markdown to Word and Apply Base style feedbacks

File-Formats-toc.html
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-65774">https://syncfusion.atlassian.net/browse/WF-65774</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Change order of Word document conversion md files
</td>
</tr>
<td>
</td>
<td>
Done
</td>
</tr>
</table>
=> WF-65244-Change order of md files

File-Formats/DocIO/Word-document/Split-Word-documents.md, File-Formats/DocIO/convert-markdown-to-word-document-in-csharp.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-65774">https://syncfusion.atlassian.net/browse/WF-65774</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Change code snippet tab names
</td>
</tr>
<td>
</td>
<td>
Not yet
</td>
</tr>
</table>
=> WF-65774-Changing code snippet tab names

File-Formats/XlsIO/Create-read-edit-excel-files-in-uwp-c-sharp.md
Added redirect links for excel.
Regards,
Sharly A.
=> SEO-3446 - File Format excel

File-Formats/DocIO/Working-with-Tables.md, File-Formats/DocIO/convert-markdown-to-word-document-in-csharp.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-65704">https://syncfusion.atlassian.net/browse/WF-65704</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Add hyperlinks for new features in DocIO
</td>
</tr>
<td>
</td>
<td>
Done
</td>
</tr>
</table>
=> WF-65704-Add hyperlinks for new features in DocIO

File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md, File-Formats/PDF/Working-with-OCR/Troubleshooting.md
Updated the troubleshooting page in OCR Section
=> WF-65722 Need to update the troubleshooting page in OCR Section

File-Formats/PDF/Working-with-Annotations.md, File-Formats/PDF/Working-with-Tagged-PDF.md
Hi @chinnumuniyappan,
Kindly review the UG documentation for Extract accessibility tags and get image from custom rubber stamp.
Content review: https://syncfusion.atlassian.net/browse/DOC-5261
Regards,
Anantha Gokula Raman J
=> WF-65875 Extract accessibility tags and get image from custom rubber stamp

File-Formats/PDF/Working-with-Annotations.md, File-Formats/PDF/Working-with-Tagged-PDF.md
Hi @chinnumuniyappan,
Kindly review the UG documentation for Extract accessibility tags and get image from custom rubber stamp.
Content review: https://syncfusion.atlassian.net/browse/DOC-5261
Regards,
Anantha Gokula Raman J
=> WF-65875 UG for extract accessibility tags and get image from custom rubber stamp.

File-Formats/PDF/NuGet-Packages-Required.md, File-Formats/PDF/Working-with-Document-Conversions.md
Hi All, 
Updated the html to PDF NuGet changes and html to SVG changes.
Regards,
Sameerkhan N
=> EJDOTNETCORE-4731 Updated the html to PDF NuGet changes and html to SVG changes.

File-Formats/DocIO/Open-and-save-Word-document-in-Blazor.md, File-Formats/DocIO/Working-with-Paragraph.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-657044">https://syncfusion.atlassian.net/browse/WF-WF-65704</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Added highlight ending tab
</td>
</tr>
<tr>
<td>
Solution
</td>
<td>
Added highlight ending tab
</td>
</tr>
<tr>
<td>
</td>
<td>
Yes
</td>
</tr>
</table>
=> WF-65704-open and save document in blazor

File-Formats/XlsIO/faqs/how-to-open-an-excel-file-with-encoding-in-net-core.md
=> WF-65951- How to open a file with encoding in .NET Core using Syncfusion XlsIO -HF

File-Formats/DocIO/faqs/migrate-from-net-framework-to-net-core.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-65984">https://syncfusion.atlassian.net/browse/WF-65984</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Made link corrections to migrating from net framework to net core
</td>
</tr>
<tr>
<td>
Solution
</td>
<td>
Made link corrections to migrating from net framework to net core
</td>
</tr>
<tr>
<td>
</td>
<td>
Pending
</td>
</tr>
</table>
=> WF-65984-Made link corrections to migrating from net framework

File-Formats/DocIO/Create-Word-document-in-Xamarin.md, File-Formats/DocIO/Open-and-save-Word-document-in-Xamarin.md, File-Formats/DocIO/Silverlight.md, File-Formats/DocIO/WinRT.md, File-Formats/DocIO/Windows-Phone.md, File-Formats/DocIO/Word-Conversion.md, File-Formats/DocIO/html.md, File-Formats/Presentation/Working-with-Animation.md, File-Formats/Presentation/Working-with-Tables.md, File-Formats/XlsIO/Excel-to-PDF-Conversion.md, File-Formats/XlsIO/create-read-edit-excel-files-in-xamarin-c-sharp.md
Worked on SEMrush changes, so merge these changes
Regards,
Gowthaman
=> SEO-171308-semrush-report-issues

File-Formats/PDF/Working-with-OCR/Features.md, File-Formats/PDF/Working-with-OCR/Working-with-OCR.md
Hi All,
OCR NuGet package update content added in UG.
Regards,
Sameerkhan N
=> EJDOTNETCORE-4726 Perform OCR NuGet package updated content.

File-Formats/DocIO/Create-Word-document-in-Blazor.md, File-Formats/DocIO/Open-and-save-Word-document-in-Blazor.md, File-Formats/DocIO/Supported-and-Unsupported-Features.md, File-Formats/Presentation/Presentation-to-PDF.md, File-Formats/Presentation/Supported-and-Unsupported-Features.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-blazor.md
<html>
<body>
Task Link | https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/826283
-- | --
Description | Modify Blazor Server side as Server app and Client side as WASM APP 
</body>
</html>
Regrads,
Venkatesh
=> ES-826283-Modify Blazor Server  and Client side Names

File-Formats/Presentation/Presentation-to-PDF.md
ES-826283-Update Presentation-to-PDF.md
=> ES-826283-Update Presentation-to-PDF with proper code tab name

File-Formats/Presentation/Presentation-to-PDF.md
<html>
<body>
Task Link | https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/826283
-- | --
Description | Modify VB.NET to vb.net in Presentation-to-PDF.md file
</body>
</html>
Regards,
Venkatesh
=> ES-826283-Modify VB.NET to vb.net

File-Formats/Presentation/Presentation-to-PDF.md
<html>
<body>
Task Link | https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/826283
-- | --
Description | Modify the Content as per Development
</body>
</html>
Regrads,
Venkatesh
=> ES-826283: Modify content as per Development

File-Formats/PDF/Working-with-Pages.md, File-Formats/PDF/Working-with-Text.md
Hi All,
I have updated code example with below three tabs in PDF UG documentation. Kindly review this and merge. 
- C# (.NET Cross platform) 
- C# (.NET Windows-specific) 
- VB.NET (.NET Windows-specific) 
UG topics:
* Working with Pages
* Working with Text
Regards,
Sowmiya L
=> 828263 - Update code example with three tabs in PDF UG documentation - Hotfix

File-Formats/PDF/Merge-Documents.md, File-Formats/PDF/Working-with-Brushes.md, File-Formats/PDF/Working-with-Document.md, File-Formats/PDF/Working-with-Flow-Layout.md, File-Formats/PDF/Working-with-Images.md
Hi All,
Organize the code snippets with three tabs .
1. C# (.NET Cross platform) 
2. C# (.NET Windows-specific) 
3. VB.NET (.NET Windows-specific) 
Topics are:
Working with document
Working with Images
Working with Brushes
Working with flow layout
Merge documents
Regards,
Sameerkhan N
=> 828264 Organize the code snippets with three tabs in working with documentation.

File-Formats/XlsIO/Excel-to-JSON-Conversion.md
Organizing the code snippets in the Excel to JSON Conversion page of XlsIO with three tabs 
=> 827344 - XlsIO - Organize code snippets in Excel to JSON Conversion - HF

File-Formats/XlsIO/Custom-XML-Support.md
Organizing the code snippets in the Custom XML Support page of XlsIO with three tabs 
=> 827345 - XlsIO - Organize code snippets in Custom XML Support - HF

File-Formats/XlsIO/Working-with-Macros.md
Organizing the code snippets in the Working with Macros page of XlsIO with three tabs 
=> 827329 - XlsIO - Organize code snippets in Working with Macros - HF

File-Formats/XlsIO/Working-with-Drawing-Objects.md
Organizing the code snippets in the Working with Drawing Objects page of XlsIO with three tabs 
=> 827327 - XlsIO - Organize code snippets in Working with Drawing Objects - HF

File-Formats/XlsIO/Security.md
Organizing the code snippets in the Security page of XlsIO with three tabs 
=> 827324 - XlsIO - Organize code snippets in Security - HF

File-Formats/XlsIO/Slicer.md
Organizing the code snippets in the Slicer page of XlsIO with three tabs 
=> 827321 - XlsIO - Organize code snippets in Slicer - HF

File-Formats/XlsIO/Working-with-Pivot-Charts.md
Organizing the code snippets in the Working with Pivot Charts page of XlsIO with three tabs 
=> 827317 - XlsIO - Organize code snippets in Working with Pivot Charts - HF

File-Formats/XlsIO/Working-with-Pivot-Tables.md
Organizing the code snippets in the Working with Pivot Tables page of XlsIO with three tabs 
=> 827315 - XlsIO - Organize code snippets in Working with Pivot Tables - HF

File-Formats/XlsIO/Working-with-Pictures.md
Organizing the code snippets in the Working with Pictures page of XlsIO with three tabs 
=> 827311 - XlsIO - Organize code snippets in Working with Pictures - HF

File-Formats/XlsIO/Excel-to-PDF-Converter-Settings.md
Organizing the code snippets in the Excel to PDF Converter Settings page of XlsIO with three tabs 
=> 827334 - XlsIO - Organize code snippets in Excel to PDF Converter Settings - HF

File-Formats/XlsIO/Worksheet-to-Image-Conversion.md
Organizing the code snippets in the Worksheet to Image Conversion page of XlsIO with three tabs 
=> 827337 - XlsIO - Organize code snippets in Worksheet to Image Conversion - HF

File-Formats/XlsIO/create-excel-file-csharp-vbnet.md
Organizing the code snippets in the Getting Started page of XlsIO with three tabs  
=> 827238 - XlsIO - Organize code snippets in Getting Started - HF

File-Formats/DocIO/Convert-Word-Document-to-PDF-in-ASP-NET-Core.md, File-Formats/DocIO/Convert-Word-Document-to-PDF-in-ASP-NET-MVC.md, File-Formats/DocIO/Convert-Word-Document-to-PDF-in-Blazor.md, File-Formats/DocIO/Convert-Word-Document-to-PDF-in-UWP.md, File-Formats/DocIO/Convert-Word-Document-to-PDF-in-WPF.md, File-Formats/DocIO/Convert-Word-Document-to-PDF-in-WinUI.md, File-Formats/DocIO/Convert-Word-Document-to-Pdf-in-Window-Forms.md, File-Formats/DocIO/Convert-Word-Documnet-to-PDF-ASP-NET.md
Hi All,
Modify the Title and Description for convert  Word to PDF all subpages .
Regards,
Venkatesh
=> ES-827992-Change title and Description

File-Formats/PDF/Working-with-Text-Extraction.md
Hi All,
The extract text with boolean overload is properly updated with a API link.
Regards,
Sameerkhan N
=> 829747 Added correct API link for working with extract text topics.

File-Formats/XlsIO/Working-with-Cell-or-Range-Formatting.md
Organizing the code snippets in the Working with Cell or Range Formatting page of XlsIO with three tabs 
=> 827289 - XlsIO - Organize code snippets in Working with Cell or Range Formatting - HF

File-Formats/XlsIO/Worksheet-Cells-Manipulation.md
Organizing the code snippets in the Worksheet Cells Manipulation page of XlsIO with three tabs 
=> 827288 - XlsIO - Organize code snippets in Worksheet Cells Manipulation - HF

File-Formats/XlsIO/Worksheet-Rows-and-Columns-Manipulation.md
Organizing the code snippets in the Worksheet Rows and Columns Manipulation page of XlsIO with three tabs 
=> 827283 - XlsIO - Organize code snippets in Worksheet Rows and Columns Manipulation - HF

File-Formats/XlsIO/Working-with-Excel-Tables.md
Organizing the code snippets in the Working with Tables page of XlsIO with three tabs 
=> 827308 -XlsIO - Organize code snippets in Working with Tables - HF

File-Formats/XlsIO/Working-with-Data-Validation.md
Organizing the code snippets in the Working with Data Validation page of XlsIO with three tabs 
=> 827298 - XlsIO - Organize code snippets in Working with Data Validation - HF

File-Formats/DocIO/NuGet-Packages-Required.md, File-Formats/Presentation/NuGet-Packages-Required.md
Hi All,
Added the Hyperlink for Nuget Package Required file.
Regards
venkatesh
=> ES-827992-Hyperlink Added for Nuget Package Required

File-Formats/introduction.md
Please review extension changes.
Regards,
Sharly A.
=> SEO-172146 - File Format

File-Formats-toc.html
Hi All,
Modify the name BLAZOR to Blazor in toc file.
Regards
Venkatesh
=> ES-827992: Modify the name BLAZOR to Blazor in toc file

File-Formats/DocIO/Working-with-Mathematical-Equation.md
Hi All,
Tab is not closed properly in Woking with Mathematical equation md file
Regards
Venkatesh
=> ES-829615:Tab is not closed properly

File-Formats/DocIO/Working-with-Mathematical-Equation.md, File-Formats/DocIO/Working-with-Table-Of-Contents.md
Hi All,
Tab is not closed properly in these md file.
Regards
Venkatesh
=> ES-829615: Tab is not closed properly

File-Formats/XlsIO/Working-with-Data.md
Organizing the code snippets in the Working with Data page of XlsIO with three tabs 
=> 827291 - XlsIO - Organize code snippets in Working with Data - HF

File-Formats/XlsIO/Working-with-Formulas.md
Organizing the code snippets in the Working with Formulas page of XlsIO with three tabs 
=> 827294 - XlsIO - Organize code snippets in Working with Formulas - HF

File-Formats/XlsIO/Working-with-Conditional-Formatting.md
Organizing the code snippets in the Working with Conditional Formatting page of XlsIO with three tabs 
=> 827296 - XlsIO - Organize code snippets in Working with Conditional Formatting - HF

File-Formats/XlsIO/Working-with-Charts.md
Organizing the code snippets in the Working with Charts page of XlsIO with three tabs 
=> 827302 - XlsIO - Organize code snippets in Working with Charts - HF

File-Formats/XlsIO/Working-with-Template-Markers.md
Organizing the code snippets in the Working with Template Markers page of XlsIO with three tabs 
=> 827305 - XlsIO - Organize code snippets in Working with Template Markers - HF

File-Formats/DocIO/Working-with-Table-Of-Contents.md
ES-829615-Resolved-end-highlight-issue in DocIO
=> ES-829615-Resolved-end-highlight-issue in DocIO

File-Formats-toc.html
Hi All,
I removed subpage Hyperlink in Convert word to PDF 
Regards
Venkatesh
=> Es-829615: Removed_hyperlink_in_toc_file

File-Formats/DocIO/Working-with-Fields.md
Hi All,
Code not properly updated for VB.net tab
Regards,
Venkatesh
=> ES-829615-VB.Net_snippet_code_not_properly_updated

File-Formats/DocIO/Working-with-Fields.md
Hi All,
Code not properly updated for VB.net tab
Regards,
Venkatesh
=> ES-829615: Endhighlight Issue

File-Formats-toc.html
Hi ALL,
Add Hyperlink for Convert Word to PDF  in toc file
Regards
Venkatesh
=> ES-829615: Add_Hyperlink_for_Convert_Word_to_PDF _in_toc_file

File-Formats/DocIO/Working-with-Fields.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/825214">ES-825214</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Fix compilation issue in MD file.
</td>
</tr>
<tr>
<td>
Solution
</td>
<td>
Fixed compilation issue in MD file due to code snippet tab name changes.
</td>
</tr>
</table>
=> ES-825214-Fixed compilation issue in MD file

File-Formats/PDF/Working-with-Images.md
Hi All,
Resolved the reflected changes issue in working with image md files.
Regards,
Sameerkhan N
=> 829351A Resolved the reflected changes issue in working with image md files

File-Formats/DocIO/Convert-Word-Document-to-PDF-in-Azure-App-Service-Linux.md
Hi All,
Add the proper github link for Azure App Service-Linux md file
Regards
Venkatesh
=> ES-829615: Add_proper_github_link_for_Azure_App_Service_Linux_md_file

File-Formats/introduction.md
Kindly review the changes for file format (changed http to https).
Regards,
Sharly A.
=> SEO-172146 - Introduction http to https link

File-Formats/PDF/Convert-HTML-To-PDF/net-core.md
Hi Sir,
Added the HTML to PDF video link in UG. Kindly review this.
Regards,
Jeyalakshmi T
=> 830607 Added the HTML to PDF video link in UG

File-Formats/Presentation/create-read-edit-powerpoint-files-in-asp-net-core-c-sharp.md
Kindly review the changes for duplicate description.
Regards,
Sharly A.
=> SEO-172146 - Presentation duplicate description

File-Formats/XlsIO/Worksheet-to-Image-Conversion.md
Changes made in UG for Gradient Fill support in Worksheet to Image conversion
=> 832137 - Gradient Fill support in Worksheet to Image conversion - Dev

File-Formats/Presentation/Working-with-find-and-replace.md
Hi All,
Completed Find and Replace using Regex pattern documentation in Presentation
Regards
Venkatesh
=> ES-822436: Find_and_Replace_using_Regex_pattern

File-Formats/PDF/Working-with-OCR/Features.md
Hi All,
<html>
<body>
1.Added OCR API changes in UG.
<span><span class="ui-provider gt b c d e f g h i j k l m n o p q r s t u v w x y z ab ac ae af ag ah ai aj ak" dir="ltr"><p>&nbsp;</p>
Current API | Alternate API | Return Type | Class Name
-- | -- | -- | --
PerformOCR(System.Drawing.Bitmap) | PerformOCR(System.IO.Stream) | PdfDocument | OCRProcessor
PerformOCR(System.Drawing.Bitmap, string) | PerformOCR(System.IO.Stream, string) | string | OCRProcessor
PerformOCR(System.Drawing.Bitmap, string, OCRLayoutResult) | PerformOCR(System.IO.Stream, string, OCRLayoutResult) | string | OCRProcessor
System.Drawing.RectangleF[]PageRegions | Syncfusion.Drawing.RectangleF[]PageRegions | Syncfusion.Drawing.RectangleF[] | PageRegion
System.Drawing.Rectangle | Syncfusion.Drawing.Rectangle | Rectangle …
=> 832548 Added OCR API changes in UG.

File-Formats/DocIO/Convert-Word-Document-to-PDF-in-Azure-App-Service-Linux.md, File-Formats/DocIO/Convert-Word-Document-to-PDF-in-Azure.md, File-Formats/DocIO/NuGet-Packages-Required.md
Hi ALL,
Nugget Package version change for Azure app service
Regards
Venkatesh
=> ES-829648: Nuget_Package_Version_Change

File-Formats/Presentation/Working-with-find-and-replace.md
Hi All,
Remove the pattern word in the Find and Replace using Regex
Regards,
venkatesh
=> ES-822436: Remove_Pattern_Word_in_Find_and_Replace

File-Formats/DocIO/Open-and-save-Word-document-in-ASP-NET-Core.md, File-Formats/DocIO/Open-and-save-Word-document-in-ASP-NET-MVC.md, File-Formats/DocIO/Open-and-save-Word-document-in-ASP-NET.md, File-Formats/DocIO/Open-and-save-Word-document-in-Blazor.md, File-Formats/DocIO/Open-and-save-Word-document-in-Linux.md, File-Formats/DocIO/Open-and-save-Word-document-in-MAUI.md, File-Formats/DocIO/Open-and-save-Word-document-in-Mac.md, File-Formats/DocIO/Open-and-save-Word-document-in-UWP.md, File-Formats/DocIO/Open-and-save-Word-document-in-WPF.md, File-Formats/DocIO/Open-and-save-Word-document-in-WinUI.md, File-Formats/DocIO/Open-and-save-Word-document-in-Windows-Forms.md, File-Formats/DocIO/Open-and-save-Word-document-in-Xamarin.md
Hi All,
Add images for Load and Savings in DocIO.
Regards
Venkatesh
=> ES-821427: Load_and _Saving_Add_Images_DocIO

File-Formats/DocIO/Convert-Word-Document-to-Image-in-Azure-App-Service-Linux.md
Hi All,
Convert Word to Image for Azure app service highlight tab is added
Regards
venkatesh
=> ES-822436: Azure_App_Service_Highlight_Issue

File-Formats/PDF/Convert-HTML-To-PDF/blazor.md
Hi All,
I have added notes for HTML to PDF in Blazor application topics. Kindly review and merge. 
Regards,
Jeyalakshmi T
=> 835025- Added Notes for HTML to PDF in Blazor application topics

File-Formats-toc.html
Hi All,
TOC file Updated.
Regards,
Venkatesh
=> ES-829657: Toc_File_Issue_Update

File-Formats/PDF/Convert-HTML-To-PDF/blazor.md
Hi All,
I have added notes for HTML to PDF in Blazor application topics. Kindly review and merge.
Regards,
Jeyalakshmi T
=> 835025- Added Notes for HTML to PDF in Blazor application topics -Hotfix

File-Formats/DocIO/Convert-Word-Document-to-Image-in-Azure-App-Service-Linux.md, File-Formats/DocIO/Convert-Word-Document-to-Image-in-Azure-App-Service-Windows.md, File-Formats/DocIO/Convert-Word-Document-to-Image-in-Azure-Functions-v1.md, File-Formats/DocIO/Convert-Word-Document-to-Image-in-Azure-Functions-v4.md, File-Formats/DocIO/Convert-Word-Document-to-Image-in-WPF.md, File-Formats/Presentation/Working-with-find-and-replace.md
Hi All,
Add GitHub Link in Presentation and Modified Word to Image  azure Output Image.
Reagards
venkatesh
=> Es 831427-Add_GitHub_Link_Presentation

File-Formats/PDF/Converting-XPS-to-PDF.md, File-Formats/PDF/Working-with-Attachments.md, File-Formats/PDF/Working-with-Bookmarks.md, File-Formats/PDF/Working-with-Headers-and-Footers.md, File-Formats/PDF/Working-with-HyperLinks.md, File-Formats/PDF/Working-with-Named-Destination.md, File-Formats/PDF/Working-with-PDF-Templates.md, File-Formats/PDF/Working-with-Redaction.md, File-Formats/PDF/Working-with-Security.md, File-Formats/PDF/Working-with-Shapes.md, File-Formats/PDF/Working-with-XFA.MD, File-Formats/PDF/Working-with-forms.md
Hi All,
I have updated code example with below three tabs in PDF UG documentation. Kindly review this and merge.
- C# (.NET Cross platform)
- C# (.NET Windows-specific)
- VB.NET (.NET Windows-specific)
**UG topics:**
1.	Working with forms
2.	Working with XFA
3.	Converting XPS to PDF
4.	Working with Hyperlinks
5.	Working with Templates 
6.	Working with headers and footers
7.	Working with Shapes
8.	Working with Bookmarks
9.	Working with Security
10.	Working with Redaction
11.	Working with attachments
12.	Working with named destination
Regards,
Sowmiya L
=> 828263 - Update PDF UG documentation with three tabs - Hotfix

File-Formats/PDF/Working-with-Barcode.md, File-Formats/PDF/Working-with-Colorspace.md, File-Formats/PDF/Working-with-Compression.md, File-Formats/PDF/Working-with-DigitalSignature.md, File-Formats/PDF/Working-with-JavaScript.md, File-Formats/PDF/Working-with-Layers.md, File-Formats/PDF/Working-with-Metadata.md, File-Formats/PDF/Working-with-PDF-Conformance.md, File-Formats/PDF/Working-with-Portfolio.md, File-Formats/PDF/Working-with-Tagged-PDF.md, File-Formats/PDF/Working-with-Watermarks.md, File-Formats/PDF/Working-with-ZUGFeRD-invoice.md, File-Formats/PDF/Working-with-action.md
Hi All,
I have updated code example with below three tabs in PDF UG documentation. Kindly review this and merge.
- C# (.NET Cross platform)
- C# (.NET Windows-specific)
- VB.NET (.NET Windows-specific)
**UG topics:** 
1.	Working with digital signature
2.	Working with barcode
3.	Working with action
4.	Working with watermarks
5.	Working with layers
6.	Working with portfolio
7.	Working with Tagged PDF
8.	Working with compression
9.	Working with PDF conformance 
10.	Working with ZUGFeRD 
11.	Working with Metadata 
12.	Working with color spaces 
13.	Working with JavaScript 
Regards,
Sowmiya L
=> 828263 - Update PDF documentation with three tabs - Hotfix

File-Formats-toc.html, File-Formats/XlsIO/FAQ.md, File-Formats/XlsIO/faqs/how-to-change-the-shape-text-font.md, File-Formats/XlsIO/faqs/how-to-find-and-highlight-data-in-Excel.md, File-Formats/XlsIO/faqs/how-to-upload-a-file-to-azure-blob-and-download-as-stream.md, File-Formats/XlsIO/faqs/how-to-vary-colors-by-point-for-line-and-column-chart.md, File-Formats/XlsIO/faqs/why-cone-chart-shows-itself-as-colum-or-bar-chart.md
[834381](https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/834381) - Font settings for shape text
[834855](https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/834855) - Why cone chart shows itself as bar or column chart type
[835309](https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/835309) - How to vary colors by point for line and column chart
[835313](https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/835313) - How to upload a file to Azure blob and download it as a stream
=> 834381-835309-834855-835313- XlsIO FAQs - HF

File-Formats-toc.html
Hi All,
Move Word to PDF pages as separate page.
Reagards
Venkatesh
=> Es-835263: Change_toc_structure_Word_to_PDF

File-Formats/PDF/Split-Documents.md
Hi Sir,
I have updated sample code for Split PDF document in UG documentation. Kindly review this.
Regards,
Jeyalakshmi T
=> 835577- Updated sample code for split PDF document- UG documentation

File-Formats/PDF/Working-with-Barcode.md
Hi All, 
I have updated the PDF barcode breaking changes in ASP.NET Core PDF UG documentation. Kindly review this and merge. 
Regards,
Sowmiya L
=> 832007 - Update PDF barcode breaking changes in ASP.NET Core PDF UG documentation - Hotfix

File-Formats-toc.html
TOC file changes made through https://github.com/syncfusion-content/fileformat-docs/pull/1089 are missing in latest hotfix. I have now added these changes.
=> XlsIO-TOC-Missed Changes-HF

File-Formats-toc.html
Hi All,
Updated Split PDF document path in UG
Regards,
Sameerkhan N
=> 837058-1 Added Split PDF document path in UG

File-Formats/DocIO/mail-merge/mail-merge-for-group.md, File-Formats/DocIO/mail-merge/mail-merge-for-nested-groups.md, File-Formats/DocIO/mail-merge/simple-mail-merge.md
Pages the has changes : 
https://help.syncfusion.com/file-formats/docio/mail-merge/simple-mail-merge
https://help.syncfusion.com/file-formats/docio/mail-merge/mail-merge-for-group
https://help.syncfusion.com/file-formats/docio/mail-merge/mail-merge-for-nested-groups
=> ES-836842-Revamp-Mail-Merge-UG-to-cover-all-APIs

File-Formats/DocIO/Overview.md, File-Formats/Presentation/Overview.md, File-Formats/XlsIO/Overview.md
Hi All,
Added Microsoft 365 in Overview for DocIO ,Presentation and Excel
Regards
Venkatesh
=> ES-835758 Microsoft 365 point added in overview

File-Formats-toc.html, File-Formats/XlsIO/Loading-and-Saving/loading-and-saving-excel-files-in-linux-c-sharp.md, File-Formats/XlsIO/create-read-edit-excel-files-in-linux-c-sharp.md
XlsIO UG for Linux Platform in Getting Started and Loading and Saving pages.
=> 836565 - Linux UG for XlsIO in Getting Started and Loading and Saving Pages - HF

File-Formats/PDF/Convert-HTML-To-PDF/features.md
Hi All, 
I have added the "Blink path" topic in HTML to PDF documentation with code example. Kindly review this and merge. 
Regards,
Sowmiya L
=> 837270 - Add blink path topic in HTML to PDF UG documentation - Hotfix

File-Formats/Presentation/NuGet-Packages-Required.md
Hi All,
Hyperlink Added in Nuget Required file Presentation
Regards
Venkatesh
=> Hyperlink Added in Nuget Required file Presentation

File-Formats/DocIO/Convert-Word-Document-to-PDF-in-Google-App-Engine.md
Hi All
Remove the CLI  word in Convert Word to PDF on GCP Highlight tab 
Regards
Venkatesh
=> ES-835758 Live Issue Resolve

File-Formats/PDF/Working-with-OCR/AWS-Textract.md, File-Formats/PDF/Working-with-OCR/Docker.md, File-Formats/PDF/Working-with-OCR/Features.md, File-Formats/PDF/Working-with-OCR/Linux.md, File-Formats/PDF/Working-with-OCR/WPF.md, File-Formats/PDF/Working-with-OCR/Windows-Forms.md, File-Formats/PDF/Working-with-OCR/aspnet-mvc.md, File-Formats/PDF/Working-with-OCR/azure.md, File-Formats/PDF/Working-with-OCR/blazor.md, File-Formats/PDF/Working-with-OCR/net-core.md
Hi All, 
I have made the below changes in PDF UG documentation. Kindly review this and merge. 
* Update OCR code example with removing tesseract binaries and tessdata path. 
* Add code example for the topic "**TesseractBinaries paths and Tesseract language data**". 
Regards,
Sowmiya L
=> 837267 - Update OCR code example with removing tesseract binaries and tessdata path - Hotfix

File-Formats/DocIO/Convert-Word-Document-to-PDF-in-ASP-NET-Core.md
Hi All,
Change docx to Docx in FormatType
Regards
Venkatesh
=> ES-831616 Change docx to Docx in FormatType

File-Formats/PDF/Convert-HTML-To-PDF/features.md
Hi All,
I have added the below topics in HTML to PDF section UG documentation. Please review this and merge.
1.PdfPagesize
2.Margin
3.Header and footer
4.Orientation
5.Pagerotation
Regards,
Jeyalakshmi T
=> 837527-Need to update the UG documentation in HTML to PDF section

File-Formats/PDF/Convert-HTML-To-PDF/features.md
Hi All,
I have modified the code snippet for Header and footer topic in HTML to PDF section UG documentation. 
Please review this and merge.
Regards,
Jeyalakshmi T
=> 837527- Modified the code snippet for Header and Footer topic in HTML to PDF section UG documentation

File-Formats/DocIO/Convert-Word-Document-to-Image-in-Linux.md, File-Formats/DocIO/Convert-Word-Document-to-PDF-in-Linux.md, File-Formats/DocIO/word-to-pdf-linux-docker.md, File-Formats/Presentation/Open-and-Save-PowerPoint-Presentation-in-ASP-NET-Core.md
Hi All,
Ft and Demo link are added for Linux and Docker platform.
Regards
venkatesh
=> ES- 834431 FT and demo link are added

File-Formats/Presentation/create-read-edit-powerpoint-files-in-asp-net-core-c-sharp.md
Hi All,
Youtube link added in Create a PowerPoint Presentation in ASP.NET Core.
Regards
Venkatesh
=> Youtube Link Added in ASP.NET Core (Presentation)

File-Formats/PDF/Convert-HTML-To-PDF/features.md
Hi All,
I have added Github link for HTML-to-PDF topics
1. Page size customization
2. Margin customization 
3. Header and footer 
4. Page orientation customization 
5. Rotate page
Kindly review this.
Regards,
Jeyalakshmi T
=> 837527-Added GitHub link for HTML-to-PDF topics

File-Formats/XlsIO/Create-read-edit-excel-files-in-maui-c-sharp.md
Modify the save code in Read Excel of XlsIO MAUI UG
=> Modify the save code in Read Excel of XlsIO MAUI UG - HF

File-Formats/DocIO/Word-document/Print-Word-documents.md
Hi All,
Remove Cross platform highlight tab from Print Word documet md file.
Regards,
Venkatesh
=> ES-838210 Remove Highlight tab

File-Formats-toc.html
Hi All,
Move Word tom PDF as separate control.
Regards,
Venkatesh
=> ES-835263 Overview WordtoPDF

File-Formats/PDF/Working-with-OCR/Working-with-OCR.md
Hi All,
I have updated the OCR sample code. Kindly review this.
Regards,
Jeyalakshmi T
=> 838563-Updated the OCR sample code

File-Formats/DocIO/Convert-Word-Document-to-Image-in-AWS.md, File-Formats/DocIO/Convert-Word-Document-to-PDF-in-AWS.md, File-Formats/DocIO/Convert-Word-Document-to-PDF-in-Google-Cloud-Platform.md, File-Formats/Presentation/Convert-PowerPoint-Presentation-to-Image-in-AWS.md, File-Formats/Presentation/Convert-PowerPoint-Presentation-to-Image-in-Azure.md, File-Formats/Presentation/Convert-PowerPoint-Presentation-to-PDF-in-AWS.md, File-Formats/Presentation/Convert-PowerPoint-Presentation-to-PDF-in-Azure.md
Hi All,
Hyper Link added for all Main Page of cloud platform.
Regards,
Venkatesh
=> ES-836244 Hyper Link added for all Main Page of cloud platform.

File-Formats-toc.html
Hi All,
Toc file updated for Word to PDF as separate control.
Reagrds
Venkatesh
=> ES 836244 Word to PDF as separate control

File-Formats/DocIO/mail-merge/mail-merge-for-nested-groups.md
Pages that has changes :
https://help.syncfusion.com/file-formats/docio/mail-merge/mail-merge-for-nested-groups
=> ES-838034-Resolving-errors-in-overloads-of-mail-merge-in-UG-pages

File-Formats/DocIO/Word-document/Iterating-Word-document-elements.md, File-Formats/DocIO/Word-document/Merging-Word-documents.md, File-Formats/DocIO/Word-document/Print-Word-documents.md, File-Formats/DocIO/word-file-formats.md, File-Formats/DocIO/word-to-image.md
Kindly review changes for File Formats weblink changes.
Regards,
Selline Rita.
=> SEO-172142 File Formats Redirect

File-Formats-toc.html
Hi @Mohan2401 , 
Kindly review and merge the changes 
Regards,
Kurmitha
=> 839447-Split the XlsIO UG for Excel processing and Excel to PDF-HF

File-Formats/PDF/Create-PDF-file-in-AWS-Lambda.md, File-Formats/PDF/Create-PDF-file-in-AWS.md, File-Formats/PDF/Loading-and-saving-document/Open-and-Save-PDF-document-AWS-Lambda.md, File-Formats/PDF/Loading-and-saving-document/Open-and-Save-PDF-document-AWS.md
Hi All,
Content review changes are updated in AWS platform steps in below topics:
1.Getting started
2.Load and Save PDF document
Regards,
Sameerkhan N
=> 839592-1 Content review changes are updated in AWS platform steps.

File-Formats/DocIO/Assemblies-Required.md, File-Formats/DocIO/Convert-Word-Document-to-Image-in-Google-Cloud-Platform.md, File-Formats/DocIO/Create-Word-Document-in-AWS.md, File-Formats/DocIO/Create-Word-Document-in-Azure.md, File-Formats/DocIO/Create-Word-Document-in-Google-Cloud-Platform.md, File-Formats/DocIO/Open-and-save-Word-document-in-AWS.md, File-Formats/DocIO/Open-and-save-Word-document-in-Azure.md, File-Formats/DocIO/Open-and-save-Word-document-in-Google-Cloud-Platform.md, File-Formats/Presentation/Convert-PowerPoint-Presentation-to-Image-in-Google-Cloud-Platform.md, File-Formats/Presentation/Convert-PowerPoint-Presentation-to-PDF-in-Google-Cloud-Platform.md, File-Formats/Presentation/Create-PowerPoint-Presentation-in-AWS.md, File-Formats/Presentation/Create-PowerPoint-Presentation-in-Azure.md, File-Formats/Presentation/Create-PowerPoint-Presentation-in-Google-Cloud-Platform.md, File-Formats/Presentation/Open-and-Save-PowerPoint-Presentation-in-AWS.md, File-Formats/Presentation/Open-and-Save-PowerPoint-Presentation-in-Azure.md, File-Formats/Presentation/Open-and-Save-PowerPoint-Presentation-in-Google-Cloud-Platform.md
Hi All,
Hyper Link added for all cloud platform both DocIO and Presentation.
Regards
venkatesh
=> ES-831603 Hyper Link added for all Main Page of cloud platform

File-Formats-toc.html
**Hotfix PR:** https://github.com/syncfusion-content/fileformat-docs/pull/1324/files
=> 839447-Split the XlsIO UG for Excel processing and Excel to PDF-Master

File-Formats-toc.html
Hi All,
Conflict reflection issue changes updated.
Regards,
sameerkhan N
=> 840526-1 Conflict reflection issue changes updated.

File-Formats-toc.html
Hi All,
Conflict issue changes updated in toc.html file.
Regards,
Sameerkhan N
=> 840526 Conflict issue changes updated in toc.html file.

File-Formats-toc.html
Hi All,
Toc file issue resolved both DocIO and Presentation.
Regards
Venkatesh.
=> ES- 831603 Toc file issue both DocIO and Presentation resolved 

File-Formats/PDF/Create-PDF-file-in-ASP-NET-Core.md
Hi All, 
I have replace images in "Create PDF document in ASP.NET Core". Kindly review this and merge. 
Regards,
Sowmiya L
=> 840656 - Replace images in "Create PDF document in ASP.NET Core" - Hotfix

File-Formats/System-Requirements.md
**Root:**
Need to add relevant details about macOS(ARM).
**Solution:**
The relevant details about macOS(ARM) have been added.
=> documentation(838589): Need to add relevant details about macOS(ARM)

File-Formats/PDF/Convert-HTML-To-PDF/blazor.md
Hi All,
I have updated the code sample & explanation for HTML to PDF.
Regards,
Jeyalakshmi T
=> 840386- Need to add the explanation for each step and update the sample

File-Formats-toc.html
Hi All,
Hyperlink added for overview page of WordtoPDF
Regards
Venkatesh
=> ES-831603 Hyperlink added for WordtoPDF

File-Formats/XlsIO/Loading-and-Saving/loading-and-saving-excel-files-in-mac-c-sharp.md
Hi @MallikaRK ,
Worked on multiple H1 and description. Kindly review.
Regards,
Amy Kingstone.
=> SEO-174801-File-formats-Multiple-H1

File-Formats/PDF/Working-with-OCR/Troubleshooting.md
Hi All,
I have added the link for OCR troubleshooting. Kindly review this.
Regards,
Jeyalakshmi T
=> 840386 -Added the link for OCR troubleshooting

File-Formats/XlsIO/convert-excel-to-pdf-in-blazor.md, File-Formats/XlsIO/convert-excel-to-pdf-in-maui.md, File-Formats/XlsIO/convert-excel-to-pdf-in-uwp.md, File-Formats/XlsIO/convert-excel-to-pdf-in-winui.md, File-Formats/XlsIO/convert-excel-to-pdf-in-xamarin.md
I have added a github sample link of Excel to PDF conversion in UWP, WinUI, Blazor, .NET MAUI and Xamarin platform for UG. Kindly review the changes.
Regards,
Kurmitha
=> Adding the Sample links of Conversion of Excel to PDF for the UG -HF

File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md, File-Formats/PDF/Working-with-OCR/Troubleshooting.md
Hi All,
I have added the width value for table properties. Kindly review this.
Regards,
Jeyalakshmi T
=> 842054: Need to update troubleshooting page in HTML to pdf and OCR.

File-Formats/DocIO/Working-with-Table-Of-Contents.md, File-Formats/DocIO/Working-with-Word-document.md, File-Formats/DocIO/working-with-mail-merge.md, File-Formats/PDF/Convert-HTML-To-PDF/Blink.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-asp-net-core-c-sharp.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-xamarin.md
Have worked on Xamarin Page with Redirect, please review.
Regards,
Yvone.
=> SEO-174775 File Format Page with Redirect

File-Formats-toc.html, File-Formats/XlsIO/Assemblies-Required-ExceltoPDF.md, File-Formats/XlsIO/Assemblies-Required.md, File-Formats/XlsIO/NuGet-Packages-Required-ExceltoPDF.md, File-Formats/XlsIO/NuGet-Packages-Required.md, File-Formats/XlsIO/Overview-ExceltoPDF.md, File-Formats/XlsIO/Overview.md
**Structure:**
- Overview
- Assemblies Required
- NuGet Packages Required
- Getting Started - platforms
- Excel to PDF conversion
- Excel to PDF converter settings
=> 842169 - Split Excel to PDF UG as per Excel library UG - HF

File-Formats-toc.html, File-Formats/PDF/Convert-HTML-To-PDF/Convert-HTML-to-PDF-in-Azure-App-Service-Linux-with-docker.md, File-Formats/PDF/Convert-HTML-To-PDF/Convert-HTML-to-PDF-in-Azure-App-Service-Linux.md, File-Formats/PDF/Convert-HTML-To-PDF/Convert-HTML-to-PDF-in-Azure-Functions-Linux.md, File-Formats/PDF/Convert-HTML-To-PDF/azure.md, File-Formats/PDF/Convert-HTML-To-PDF/mac.md, File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
Hi All, 
I have updated the below changes in HTML to PDF UG documentation. Kindly review this and merge. 
* Split the Azure topic by 3 -> Azure App Service Linux, Azure Functions Linux, and Azure App Service Linux Docker. 
* Update the note section below the description in HTML to PDF -> Azure. 
* Add one more topic in HTML to PDF troubleshooting. 
* Changed the "Chromium.app" path in HTML to PDF -> Mac. 
Regards,
Sowmiya L
=> 842500 - HTML to PDF UG changes - Hotfix

File-Formats/DocIO/Working-with-Comments.md
Hi All,
Change the VB.NET code in Inserting Comments in DocIO.
Reagards
Venkatesh
=> ES-842155 Change the VB.NET  code  in Inserting Comments 

File-Formats/Licensing/overview.md
Have changed FileFormat Page with redirect links.
Regards,
Yvone.
=> SEO-174775 FileFormat Page with Redirect

File-Formats/XlsIO/create-read-edit-excel-files-in-azure-functions-v1.md, File-Formats/XlsIO/create-read-edit-excel-files-in-azure-functions-v4.md
Liquid Exception: Liquid syntax error (line 27): 'endtabs' is not a valid delimiter for highlight tags. use endhighlight in File-Formats/XlsIO/create-read-edit-excel-files-in-azure-functions-v1.md
[Liquid Exception: Liquid syntax error (line 27): 'endtabs' is not a valid delimiter for highlight tags. use endhighlight in File-Formats/XlsIO/create-read-edit-excel-files-in-azure-functions-v4.md
=> XlsIO-ResolveAutomationFailure-HF

File-Formats/XlsIO/create-read-edit-excel-files-in-azure-functions-v1.md, File-Formats/XlsIO/create-read-edit-excel-files-in-azure-functions-v4.md
Liquid Exception: Liquid syntax error (line 27): 'endtabs' is not a valid delimiter for highlight tags. use endhighlight in File-Formats/XlsIO/create-read-edit-excel-files-in-azure-functions-v1.md
[Liquid Exception: Liquid syntax error (line 27): 'endtabs' is not a valid delimiter for highlight tags. use endhighlight in File-Formats/XlsIO/create-read-edit-excel-files-in-azure-functions-v4.md
=> XlsIO-ResolveAutomationFailure-Master

File-Formats/Presentation/Presentation-to-image.md
Hi All,
Note content changed in Convert PowerPoint Animations to Images
Regards
Venkatesh
=> ES-843425 Convert PowerPoint Animations to Images

File-Formats/PDF/Working-with-Text.md
Hi All, 
I have added the "Find text in PDF document" in PDF UG documentation with code example and GitHub sample link. Kindly review this and merge. 
Regards,
Sowmiya L
=> 844904 - Add "Find text in PDF document" topic in PDF UG documentation - Hotfix

File-Formats/XlsIO/Supported-Features-by-File-Formats.md
Update the supported feature list of XlsIO for the below features for 2023 Vol3
- Slicers
- What-If Analysis
- Threaded Comments
=> 846180 - Update the supported feature list of XlsIO for 2023 Vol3 - Development

File-Formats/PDF/Convert-HTML-To-PDF/features.md, File-Formats/PDF/Working-with-DigitalSignature.md, File-Formats/PDF/Working-with-Document.md
Hi All,
Added the UG Documentation for below Volume 3 features
1.Remove Specific Keys from the Existing Document Information
2.HTML Header and Footer
3.Get images from the existing signed signature field
Regards,
Jeyalakshmi T
=> 846230 -UG documentation for Volume 3, 2023

File-Formats/XlsIO/Excel-to-PDF-Conversion.md, File-Formats/XlsIO/Working-with-Drawing-Objects.md
I have modified the changes of definition for the Excel to PDF conversion of threaded comments. Kindly review the changes.
Regards,
Kurmitha
=> 843222- Modified the changes of definition for the threaded comments- dev

File-Formats/DocIO/Word-document/Compare Word documents.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/843418">Compare Word documents </a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Change the content of Compare Word document md file
</td>
</tr>
</table>
Regards,
Venkatesh
=> ES-843418-Modify the content of compare Word document UG

File-Formats/PDF/Convert-HTML-To-PDF/features.md, File-Formats/PDF/Working-with-OCR/Features.md
Hi,
I have added UG Documentation for the below samples,
•	Title:  Inject Custom CSS
•	Title: Inject Custom JavaScript
•	Title: Performance Optimization.
•	Title: Support to get the Image Rotation angle from OCR Processor
Regards,
=> UG-846272: volume 3 features UG

File-Formats/Presentation/Presentation-to-image.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/843418">Update content in PPTX to Image </a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Change the word worksheet to PowerPoint document in assembly required
</td>
</tr>
</table>
Regards,
Venkatesh
=> ES-843418 - Update the content in PPTX to Image

File-Formats/DocIO/word-to-image.md, File-Formats/DocIO/word-to-pdf.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/843418">Add Youtube Links in Word to PDF and Images</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Add youtube link in Word to PDF and Word to Image
</td>
</tr>
</table>
Regards,
Venkatesh
=> ES-847224-Add Youtube Links in Word to PDF and Images

File-Formats/PDF/Create-PDF-file-in-C-Sharp-VB-NET.md, File-Formats/PDF/Working-with-Compression.md, File-Formats/PDF/Working-with-OCR/Working-with-OCR.md, File-Formats/PDF/Working-with-forms.md
Hi All,
I have added published video links in PDF UG documentation. Kindly review this.
Regards,
=> 847395 : Need to add published video links in PDF UG documentation 

File-Formats/PDF-to-image/Convert-PDF-file-to-Image-in-ASP-NET-Core.md, File-Formats/PDF-to-image/Referring-PDFium.md
UG Content for PdfToImageConverter
=> UG Content for PdfToImageConverter

File-Formats/DocIO/Working-with-Find-and-Replace.md, File-Formats/Presentation/create-read-edit-powerpoint-files-in-xamarin.md, File-Formats/installation/offline-installer/how-to-download.md
Have changed Page with Redirect.
Regards,
Yvone.
=> SEO-175659 File format Page with Redirect

File-Formats/Presentation/Presentation-to-image.md
Hi all,
- With this PR, we modified the Animation converter sample link in Presentation library samples.
Regards,
Dharanitharan A
=> ES-846833-Modified the Animation converter sample link in Presentation library samples

File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
Hi All,
I have added proper highlight tag in trouble shooting page in HTML to PDF. Kindly review this.
Regards,
=> 848740: Added proper highlight tag.

File-Formats/XlsIO/Working-with-Charts.md
I have added a Manual Layout for chart elements. Kindly review the changes.
Regards,
Kurmitha
=> 849268 - Add code for the Manual layout in chart creation -HF

File-Formats/Presentation/Presentation-to-PDF.md
Committed the changes for adding the video file of Presentation to PDF
=> Added the Presentation to PDF video in Presentation-to-PDF.md

File-Formats-toc.html
Hi All,
I have added mac link in File-Formats-toc.html. Kindly review this.
Regards,
=> 848740_add_mac:  added a mac link.

File-Formats/PDF/Working-with-Redaction.md, File-Formats/PDF/Working-with-Tagged-PDF.md
Hi All,
I have added published video link in PDF UG documentation. Kindly review this.
Topic: How to Create Accessible PDF Documents in .NET using the PDF Library
How to Redact PDF Documents in .NET using the PDF Library
Regards,
Jeyalakshmi T
=> 848818 -Added published video links in PDF UG documentation

File-Formats/PDF/Working-with-OCR/Troubleshooting.md
Hi All,
I have updated the binaries path package structure in OCR section. Kindly review this.
Regards,
Jeyalakshmi T
=> 851787 - Need to revamp the OCR troubleshooting section

File-Formats/PDF/Working-with-Pages.md
Hi All,
I have revamped the UG documentation in Page section. Kindly review this.
Regards,
Jeyalakshmi T
=> 852386 -Revamp the UG documentation

File-Formats/Presentation/Getting-Started.md
Hi All,
Youtube link added in getting started a PowerPoint presentation.
Task Link: [Add youtube link in Getting started in PowerPoint](https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/847220)
Regards
Venkateh
=> ES-838210 Youtube link added in getting started a PowerPoint presentation

File-Formats/XlsIO/create-excel-files-in-console-apps-c-sharp.md
I have changed the ASP .Net core to .Net core in UG for console applications for create Excel. Kindly review the changes.
Regards,
Kurmitha
=> 850177 - Change the ASP.Net core to .Net core in ConsoleApps Getting Started - HF

File-Formats/DocIO/html.md
HI All,
I completed the Cross Platform code added in  Customize  the Word to HTML 
Task Link: <a href="https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/852981">Add cross platform code for Customizing Word to HTML</a>
Regards
Venkatesh
=> ES-852981 Customize  the Word to HTML 

File-Formats/DocIO/html.md
Hi All,
UG drafted for Customize image path in Word to HTML.
Task Link: <a href="https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/852985">Add information about Imagenodevisited event in Word to HTML</a>
Regards
Venkatesh
=> ES-852985 Customize Image path

File-Formats/PDF/Working-with-DigitalSignature.md
Hi All,
I have revamped the UG documentation in digital signature section. Kindly review this.
Regards,
Jeyalakshmi T
=> 852386 - Revamp the UG documentation

File-Formats/DocIO/Create-Word-document-in-ASP-NET-Core.md, File-Formats/DocIO/Getting-Started.md, File-Formats/DocIO/Working-with-Security.md
Hi All,
Add YouTube link in getting started in DocIO
Add Youtube link in Encrypt and Decrypt in DocIO.
Task Link: <a href="https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/847220/">Add YouTube link in getting started in DocIO</a>
Regards,
Venkatesh
=> ES-847220- Add YouTube link in getting started in DocIO

File-Formats/DocIO/word-to-pdf.md
Updated hyperlink in word-to-pdf.md
=> Update hyperlink in word-to-pdf.md

File-Formats/DocIO/html.md
Hi All,
Remove unwanted tab in HTML.md file
Regards
Venkatesh
=> ES-853955 -  Remove unwanted tab in HTML.md file

File-Formats/PDF/Working-with-Text-Extraction.md
Hi All,
I have added  the text extraction video link in PDF UG documentation. Kindly review this.
Regards,
Jeyalakshmi T
=> 854301 -Added Text Extraction video link in PDF UG documentation 

File-Formats-toc.html
Hi All,
Toc File modified for working with charts in DocIO.
Regards
Venkatesh
=> ES- 852595 TOC file modified in working with charts in DocIO product

File-Formats/PDF/Working-with-OCR/Dot-NET-Core.md
Hi @MallikaRK ,
Please review the redirect links changes made.
Thanks.
Regards,
Edith.
=> SEO-176496-FileFormat-UG-page-with-redirects-links

File-Formats/DocIO/html.md
Hi All,
Add space in Note on Html.md file
Regards
Venkatesh
=> ES-852981- Issue Resolved in Note

File-Formats-toc.html, File-Formats/DocIO/Working-with-Charts/Chart-Area.md, File-Formats/DocIO/Working-with-Charts/Chart-Axis.md, File-Formats/DocIO/Working-with-Charts/Chart-Data-Lables.md, File-Formats/DocIO/Working-with-Charts/Chart-Legend.md, File-Formats/DocIO/Working-with-Charts/Chart-Plot-Area.md, File-Formats/DocIO/Working-with-Charts/Chart-Series.md, File-Formats/DocIO/Working-with-Charts/Chart-Title.md
Hi All,
Feedback addressed in chart element in DocIO.
Task Link: <a href="https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/854348/">Revamp chart UG in DocIO</a>
Regards
Venkatesh
=> ES-854348-Feedback addressed in chart element in DocIO

File-Formats-toc.html, File-Formats/DocIO/Working-with-Charts/Chart-Area.md, File-Formats/DocIO/Working-with-Charts/Chart-Axis.md, File-Formats/DocIO/Working-with-Charts/Chart-Data-Lables.md, File-Formats/DocIO/Working-with-Charts/Chart-Legend.md, File-Formats/DocIO/Working-with-Charts/Chart-Plot-Area.md, File-Formats/DocIO/Working-with-Charts/Chart-Series.md, File-Formats/DocIO/Working-with-Charts/Chart-Title.md, File-Formats/Presentation/Working-with-Charts/Chart-Area.md, File-Formats/Presentation/Working-with-Charts/Chart-Axis.md, File-Formats/Presentation/Working-with-Charts/Chart-Data-Labels.md, File-Formats/Presentation/Working-with-Charts/Chart-Legend.md, File-Formats/Presentation/Working-with-Charts/Chart-Plot-Area.md, File-Formats/Presentation/Working-with-Charts/Chart-Series.md, File-Formats/Presentation/Working-with-Charts/Chart-Title.md
Hi All,
Completed Revamp chart in Presentation.
Task Link: <a href="https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/854348/">Revamp chart UG in Presentation</a>
Regards
Venkatesh
=> ES-854348- Revamp chart in Presentation Product 

File-Formats/XlsIO/create-excel-file-csharp-vbnet.md, File-Formats/XlsIO/create-excel-files-in-console-apps-c-sharp.md
I have add the Video for creating Excel in Getting Started and modify the console ug notes. Kindly review the changes.
Regards,
Kurmitha
=> 855254 - Add the Video for creating Excel in Getting Started -HF

File-Formats/Presentation/SmartArt.md
Hi All,
SmartArt you-tube link added in Presentation product.
Task link : <a href="https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/847220/">Yotube link add in SmartArt</a>
Regards
Venkatesh
=> ES-847220-SmartArt you-tube link added in Presentation product.

File-Formats/XlsIO/Chart-to-Image-Conversion.md
I have changed the image path. Kindly review the changes.
Regards,
Kurmitha
=> 855441- Image Stretching Issues in XlsIO - Hotfix

File-Formats/XlsIO/Chart-to-Image-Conversion.md
I have changed the image path. Kindly review the changes.
Regards,
Kurmitha
=> 855441- Image Stretching Issues in XlsIO - Development

File-Formats/XlsIO/Create-read-edit-excel-files-in-asp-net-core-c-sharp.md, File-Formats/XlsIO/Create-read-edit-excel-files-in-blazor-c-sharp.md, File-Formats/XlsIO/Create-read-edit-excel-files-in-uwp-c-sharp.md, File-Formats/XlsIO/Create-read-edit-excel-files-in-windows-forms-c-sharp.md, File-Formats/XlsIO/Create-read-edit-excel-files-in-winui-c-sharp.md, File-Formats/XlsIO/Create-read-edit-excel-files-in-wpf-c-sharp.md, File-Formats/XlsIO/create-read-edit-excel-files-in-asp-net-c-sharp.md, File-Formats/XlsIO/create-read-edit-excel-files-in-asp-net-mvc-c-sharp.md, File-Formats/XlsIO/create-read-edit-excel-files-in-xamarin-c-sharp.md
I have changed the image path for the ASP.NET Core, ASP.NET MVC, ASP.NET, WinUI, WPF, UWP, WinForms, Blazor and Xamarin. Kindly review the changes.
Regards,
Kurmitha
=> 855441- Change the Image path for the XlsIO Getting Started - Hotfix

File-Formats/XlsIO/Create-read-edit-excel-files-in-maui-c-sharp.md, File-Formats/XlsIO/create-excel-files-in-console-apps-c-sharp.md, File-Formats/XlsIO/create-read-edit-excel-files-in-aws-lambda.md, File-Formats/XlsIO/create-read-edit-excel-files-in-azure-app-service-linux.md, File-Formats/XlsIO/create-read-edit-excel-files-in-azure-app-service-windows.md, File-Formats/XlsIO/create-read-edit-excel-files-in-azure-functions-v1.md, File-Formats/XlsIO/create-read-edit-excel-files-in-azure-functions-v4.md, File-Formats/XlsIO/create-read-edit-excel-files-in-google-app-engine.md, File-Formats/XlsIO/create-read-edit-excel-files-in-mac-c-sharp.md
I have changed the image path for the Mac, Maui, Console, Azure, AWS and GCP. Kindly review the changes.
Regards,
Kurmitha
=> 855441- Change the Image path for the remaining platform of Getting Started in XlsIO - Hotfix 

File-Formats/DocIO/Word-document/Compare-Word-documents.md
Hi All,
Youtube link added for compare Word documents.
Task Link:<a href="https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/847220">Youtube link added for compare Word documents</a>
Regards
Venkatesh
=> ES-847220 - Youtube link added for compare Word documents

File-Formats/DocIO/Working-with-Find-and-Replace.md, File-Formats/DocIO/Working-with-Word-document.md, File-Formats/DocIO/html.md, File-Formats/DocIO/word-to-pdf.md
Added how to resolve font problem KB and How to convert multiple Word documents to multiple PDFs and zip the PDFs KB in Word to PDF See Also page
=> ES-261545 Add how to resolve font problem KB in Word to PDF See Also page

File-Formats/DocIO/Create-Word-document-in-Console-application.md, File-Formats/DocIO/Open-and-save-Word-document-in-Console-application.md, File-Formats/Presentation/Create-PowerPoint-in-Console-application.md, File-Formats/Presentation/Open-and-Save-PowerPoint-in-Console-application.md
HI All,
Feedback addressed in Console application both DocIO and Presentation.
Task Link:<a href="https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/855596">Create UG for Console Application for DocIO and Presentation</a>
Regards,
Venkatesh
=> ES- 855596 Feedback addressed in Console application both DocIO and Presentation

File-Formats/DocIO/Open-and-save-Word-document-in-ASP-NET-Core.md
Modified Word document open code in loading and saving UG page
=> ES-855704-Modify-Word-document-open-code-in-loading-and-saving-UG-page

File-Formats/XlsIO/Loading-and-Saving/loading-and-saving-excel-files-in-maui-c-sharp.md
Hello,
I have worked on the multiple H1
Regards,
Beryl.
=> SEO-176113-XLSIO-Multiple-H1

File-Formats/Presentation/Working-with-PowerPoint-presentation.md
Hi All,
Add **FirstSlideNumber** API code snippets in UG
TaskLink: <a href="https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/850323">Add FirstSlideNumber API code snippets in UG</a>
Regards,
Venkatesh
=> ES-850323 - Add FirstSlideNumber API code snippets in UG

File-Formats/XlsIO/create-excel-file-csharp-vbnet.md
I have changed the image path. Kindly review the changes.
Regards,
Kurmitha
=> 855441 - Image Stretching Issues in Getting Started - Hotfix

File-Formats/DocIO/Working-with-Charts.md, File-Formats/Presentation/Working-with-Charts.md
Hi All,
Modify the sentence the chart redirect link in DocIO and Presentation product
Task Link: <a href="https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/854348">Revamp chart UG in Presentation</a>
Regards
Venkatesh
=> ES-854348 Modify the sentence the chart redirect link in DocIO and Presentation 

File-Formats/DocIO/Charts/Chart-Area.md, File-Formats/DocIO/Charts/Chart-Axis.md, File-Formats/DocIO/Charts/Chart-Data-Lables.md, File-Formats/DocIO/Charts/Chart-Legend.md, File-Formats/DocIO/Charts/Chart-Plot-Area.md, File-Formats/DocIO/Charts/Chart-Series.md, File-Formats/DocIO/Charts/Chart-Title.md, File-Formats/DocIO/Open-and-save-Word-document-in-Linux.md, File-Formats/DocIO/Open-and-save-Word-document-in-MAUI.md, File-Formats/DocIO/Open-and-save-Word-document-in-Mac.md, File-Formats/DocIO/Open-and-save-Word-document-in-UWP.md, File-Formats/DocIO/Open-and-save-Word-document-in-WinUI.md, File-Formats/DocIO/Open-and-save-Word-document-in-Xamarin.md, File-Formats/Presentation/Charts/Chart-Area.md, File-Formats/Presentation/Charts/Chart-Axis.md, File-Formats/Presentation/Charts/Chart-Data-Labels.md, File-Formats/Presentation/Charts/Chart-Legend.md, File-Formats/Presentation/Charts/Chart-Plot-Area.md, File-Formats/Presentation/Charts/Chart-Series.md
Hi All,
1. Github link added for Chart both DocIO and Presentation product
2. Github link added for Loading and Saving in DocIO.
Task Link : <a href="https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/854348">Revamp chart UG in Presentation</a>
Regards,
Venkatesh
=> ES-854348 Github link added for Chart both DocIO and Presentation product

File-Formats-toc.html
Added the new page for Console applications in PDF UG documentation
=> 856144 -Need to create the new page for Console applications in PDF UG documentation-Hotfix

File-Formats-toc.html
Added the new page for Console applications in PDF UG documentation
=> 856144 -Need to create the new page for Console applications in PDF UG documentation-Master

File-Formats/PDF/Working-with-OCR/AWS-Textract.md
I have replaced the code snippet for AWS Textract in OCR section
=> 859144 -Need to revamp the AWS Textract in PDF UG documentation

File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
Updated the troubleshooting in HTML to PDF.
=> 856144 -Need to update the troubleshooting in HTML to PDF-Development

File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
Updated the troubleshooting in HTML to PDF.
=> 860395 -Updated the troubleshooting in HTML to PDF

File-Formats/PDF/Working-with-Watermarks.md
Added the Watermarks and Bookmarks to a PDF video link in PDF UG documentation
=> 860472 -Added the Watermarks and Bookmarks to a PDF video link in PDF UG documentation

File-Formats/DocIO/Assemblies-Required.md, File-Formats/DocIO/FAQ.md, File-Formats/DocIO/Getting-Started.md, File-Formats/DocIO/Working-with-Charts.md, File-Formats/DocIO/word-to-image.md, File-Formats/DocIO/word-to-pdf.md, File-Formats/Presentation/Assemblies-Required.md, File-Formats/Presentation/Presentation-to-PDF.md, File-Formats/Presentation/Presentation-to-image.md, File-Formats/Presentation/Working-with-Charts.md
Hi All,
Task ID: https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/159323
With this MR, we have documented the fallback font functionality for DocIO and Presentation UG. And also modified the API of the Refresh in chart.
Regards,
Lokesh B
=> ES-853397-Add fallback font code snippets in UG documentation

File-Formats/DocIO/Working-with-LaTeX.md
Removed unwanted content from LaTeX to Math UG
=> ES-859053 - Removing unwanted content from LaTeX to Math UG - Development

File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
Updated the UG documentation for HTMLtoPDF conversion section
=> 861671 -Need to update the UG documentation for HTMLtoPDF conversion section

File-Formats/Presentation/Comments.md
Added UG note about modern comments are not supported in current Essential Presentation
=> ES-818182 Add UG note about modern comments are not supported in current Essential Presentation

File-Formats-toc.html
HI All,
TOC file updated in DocIO product
Regards
Venkatesh
=> ES 861360 TOC file updated in DocIO product

File-Formats-toc.html
=> 178067 - TOC File Updated - dev

File-Formats/DocIO/installation/offline-installer/how-to-download.md, File-Formats/DocIO/installation/offline-installer/how-to-install.md, File-Formats/DocIO/installation/web-installer/how-to-download.md, File-Formats/DocIO/installation/web-installer/how-to-install.md, File-Formats/PDF/installation/offline-installer/how-to-download.md, File-Formats/PDF/installation/offline-installer/how-to-install.md, File-Formats/PDF/installation/web-installer/how-to-download.md, File-Formats/PDF/installation/web-installer/how-to-install.md, File-Formats/Presentation/installation/offline-installer/how-to-download.md, File-Formats/Presentation/installation/offline-installer/how-to-install.md, File-Formats/Presentation/installation/web-installer/how-to-download.md, File-Formats/Presentation/installation/web-installer/how-to-install.md, File-Formats/XlsIO/installation/offline-installer/how-to-download.md, File-Formats/XlsIO/installation/offline-installer/how-to-install.md, File-Formats/XlsIO/installation/web-installer/how-to-download.md, File-Formats/XlsIO/installation/web-installer/how-to-install.md
Updated file-formats platform name in newly added md files
=> 178067-Updated platforms name in new md files - dev

File-Formats/DocIO/Working-with-Comments.md
Task Link: https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/854221 
Added details for "How to check comment is resolved or not in Word document".
=> ES-854221 - How to check comment is resolved or not in Word document - HF

File-Formats/DocIO/word-to-image.md, File-Formats/DocIO/word-to-pdf.md, File-Formats/Presentation/Presentation-to-PDF.md, File-Formats/Presentation/Presentation-to-image.md
Hi All,
Task ID: https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/159323 
With this MR, we have added the github sample link for the fallback font code snippet for DocIO and Presentation UG.
Regards,
Lokesh B
=> ES-853397-Added github sample link for the fallback font code snippet

File-Formats/PDF/Split-Documents.md
Hi All,
Added UG documentation for Import Tagged structure when Splitting PDF Documents.
Regards,
Jeyalakshmi T
=> 862721-UG documentation Volume 4 features - Split Tags

File-Formats/DocIO/Working-with-LaTeX.md
HI All,
GitHub and API link added in LaTeX.
Regards,
Venkatesh
=> ES 861360 GitHub and API link added in LaTeX 

File-Formats-toc.html
HI All,
Toc file updated in DocIO and Presentation product.
Regards
venkatesh
=> ES-861360 Toc file updated in DocIO and Presentation product.

File-Formats-toc.html
Hi,
Here we added UG documentation for save PDF to various platforms and open PDF from various platforms like Google drive, Google cloud storage, Azure cloud storage, AWS and Dropbox.
Regards,
Srihariharan Gopalakrishnan.
=> 851874: Save and open PDF file to various storage

File-Formats/DocIO/Convert-Word-Document-to-Image-in-Blazor.md, File-Formats/DocIO/Convert-Word-Document-to-PDF-in-Blazor.md, File-Formats/Presentation/Convert-PowerPoint-to-Image-in-Blazor.md, File-Formats/Presentation/Convert-PowerPoint-to-PDF-in-Blazor.md, File-Formats/Presentation/FAQ.md
Hi All ,
I have appended the content in the note tab of the Blazor WebAssembly (WASM) and removed the TIFF image limitations in the FAQ page. Kindly review the changes.
Regards,
Anto Nihil S
=> ES-820123-Appended the content in note tab of the Blazor WebAssembly (WASM)

File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
Hi All,
I have added the UG documentation for Background color missing issue in HTML Header and Footer.
Regards,
=> 864873: Background color missing issue in HTML Header and Footer.

File-Formats/PDF/Working-with-DigitalSignature.md
Hi team,
Here i have added a proper work sample for adding a timestamp to PDF document.
Regards,
=> 865806: Adding a timestamp to PDF document not working issue.

File-Formats/PDF/Convert-HTML-To-PDF/features.md
Hi team,
I have added the UG documentation sample for Scale property in HTML converter.
Regards,
=> 865893: Need to add the UG documentation for Scale property in HTML converter.

File-Formats/DocIO/Supported-and-Unsupported-Features.md
Added the details of custom shape in Supported and Unsupported Features UG page
=> ES-860333 Update the details of custom shape in Supported and Unsupported Features UG page

File-Formats-toc.html, File-Formats/XlsIO/Create-read-edit-excel-files-in-blazor-c-sharp.md
Hi @Mohan2401,
I have modified the file path to create and edit Excel file in blazor web app.
Regards,
Kurmitha
=> 866166 - Change the file path of Blazor Web App UG- Hotfix 

File-Formats/DocIO/Working-with-LaTeX.md
Kindly review the below pull request and let me know your feedback.
<div dir="auto">
<div dir="auto">
<div dir="auto">
<table>
<tbody>
<tr style="height: 35px;">
<td style="height: 35px;">
<p dir="auto">Task Link</p>
</td>
<td style="height: 35px;">
<p dir="auto"><a href="https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/260166#4123188">UG documentation 260166: Modify the existing code snippets in PPTX to image conversion in UG - Boards (azure.com)</a></p>
</td>
</tr>
<tr style="height: 35.3333px;">
<td style="height: 35.3333px;">
<p dir="auto">Description</p>
</td>
<td style="height: 35.3333px;">
<p dir="auto">Resolved curly braces in LaTeX UG DocIO</p>
</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
=> ES-260166-Resolved curly braces in LaTeX UG DocIO

File-Formats/DocIO/Assemblies-Required.md, File-Formats/Presentation/Assemblies-Required.md
=> ES-862221-Updated required assemblies in DocIO and Presentation

File-Formats-toc.html, File-Formats/XlsIO/convert-excel-to-image-in-google-app-engine.md
Hi @Mohan2401,
I have added a file path for GCP in worksheet to image conversion.
Regards,
Kurmitha M.
=> Changes-in-XlsIO-UG

File-Formats/PDF/Supported-and-Unsupported-Features.md
Hi team,
Here I Revamped the outdated UG documentation for Supported and unsupported features.
Regards,
Srihariharan G
=> 865451: Revamp the outdated UG documentation for Supported and unsupported features.

File-Formats/DocIO/NuGet-Packages-Required.md
Added UG note about what NuGet needs to installed in UWP when converting Word to PDF
=> ES-826608 Add UG note about what NuGet needs to installed in UWP

File-Formats-toc.html, File-Formats/XlsIO/convert-excel-to-image-in-google-app-engine.md
Hi @Mohan2401,
I have added a Highlight tag and file path for GCP in worksheet to image conversion.
Regards,
Kurmitha M.
=> Highlight_tag_Issue_in_XlsIO

File-Formats-toc.html
Hi team,
Here we removed the WebKit Html to PDF related UG documentations.
Regards,
=> 866304 : Remove unwanted url links.

File-Formats/DocIO/Working-with-LaTeX.md
Added LaTeX formatting GitHub sample for appropriate format.
=> ES-864139 - Added GitHub sample for LaTeX formatting 

File-Formats/DocIO/word-to-pdf.md
Show warning for unsupported element during Word to PDF
=> ES-261786 - Show warning for unsupported elements

File-Formats/DocIO/html.md, File-Formats/DocIO/word-to-pdf.md
Task link - https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/865560
Added content for HTMLExportBodyContentAlone API
=> ES-865560- Added content for HTMLExportBodyContentAlone API

File-Formats/DocIO/Create-Word-document-in-Linux.md, File-Formats/DocIO/Create-Word-document-in-Windows-Forms.md, File-Formats/Presentation/Convert-PowerPoint-to-PDF-in-Azure-Functions-v1.md
Hi @MallikaRK,
please review the changes made.
Thanks.
Regards,
Edith.
=> SEO-178901-FF-page-with-redirect-links

File-Formats/DocIO/Word-document/Split-Word-documents.md
=> ES-868708-Add youtube link in DocIO

File-Formats-toc.html, File-Formats/XlsIO/FAQ.md, File-Formats/XlsIO/faqs/how-to-find-and-replace-text-in-hyperlinks.md
Hi @Mohan2401,
I have added a find and replace text in hyperlinks FAQ. Kindly review the changes.
Regards,
Kurmitha M.
=> 868252- Add FAQ for find and replace text in hyperlinks - Hotfix

File-Formats/DocIO/Assemblies-Required.md, File-Formats/Presentation/Assemblies-Required.md
=> ES-862221-Update required assemblies in DocIO and Presentation

File-Formats/PDF/Working-with-Security.md
Hi team,
Here we added troubleshooting work with security page.
Regards,
Srihariharan G
=> 868485: Added the  trouble shooting section for security file.

File-Formats/XlsIO/Working-with-Charts.md
Hi @Mohan2401,
I have added a display unit for primary axis. Kindly review the changes.
Regards,
Kurmitha M.
=> 868251- Add DisplayUnit for Primary value Axis - Hotfix

File-Formats/DocIO/Convert-Word-Document-to-PDF-in-MAUI.md, File-Formats/DocIO/Convert-Word-Document-to-PDF-in-UWP.md
Hi @MallikaRK,
Worked on page with redirect.
Regards,
Sharly A.
=> SEO-179773-File-Format-docs-changes

File-Formats/PDF/Create-PDF-file-in-MaUI.md
Hi team.
Here we attached the Create PDF sample for MAUI platform in .NET 8.0 framework.
Regards,
Srihariharan G
=> 869450: Update the github sample project to .NET 8.0 in NET MAUI Platform.

File-Formats/DocIO/Working-with-LaTeX.md
Task link - https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/868758
Resolved issue
=> ES-868758 - Add UG documentation for applying math justification

File-Formats/XlsIO/Working-with-Excel-Worksheet.md
Hi @Mohan2401,
I have modified the contents of page setup settings. Kindly review the changes.
Regards,
Kurmitha M.
=> 868248 - Modify the UG contents of page setup settings-XlsIO

File-Formats/PDF/PdfGrid.md
Hi team,
Here we attached the PDF document for all grid built in styles.
Regards,
Srihariharan G
=> 869460: Attach all the grid built-int styles.

File-Formats/installation/Installation-errors.md
Hi @MallikaRK .
I have worked on redirect links.
Regards,
Beryl.
=> SEO-179782-Links-With-Redirects-FileFormat

File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
I have updated the alt text, please review on the same.
Regards,
Jeffrey
=> Updated alt text

File-Formats/PDF/Convert-HTML-To-PDF/features.md
Hi team,
Here we attached the Time out support in UG documentation.
Regards,
=> 870904: Need to add the Time out support in UG documentation.

File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
Hi team,
Here we updated the additional delay time value.
Regards,
Srihariharan G
=> 872528: HTML to PDF Converter 4 times slower in newer versions issue.

File-Formats/DocIO/Convert-Word-Document-to-PDF-in-Xamarin.md, File-Formats/DocIO/Create-Word-Document-in-Azure-App-Service-Windows.md, File-Formats/PDF-to-image/Convert-PDF-to-Image.md, File-Formats/PDF/Convert-HTML-To-PDF/net-core.md, File-Formats/PDF/Create-PDF-file-in-AWS-Lambda.md, File-Formats/Presentation/Create-PowerPoint-Presentation-in-AWS-Elastic-Beanstalk.md, File-Formats/XlsIO/create-read-edit-excel-files-in-asp-net-c-sharp.md
I have changed the redirection links.
Please review,
Regards,
Scholar
=> SEO-180368-File-Formats-Redirection

File-Formats/DocIO/Convert-Word-Document-to-PDF-in-Xamarin.md
Hi @MallikaRK ,
Kindly review the changes.
Regards,
Edith.
=> SEO-180458-FF-ug-page-with-redirect-links

File-Formats/Presentation/Working-with-images.md
Hi All,
UG draft work for completed for Crop picture in presentation
Task Link: <a href="https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/864081">Add picture cropping code snippets in UG documentation</a>
Regards
Venkatesh
=> ES-864081  Crop image in Presentation

File-Formats/PDF/Working-with-PDF-Conformance.md
Hi All,
Here we added supported platform for conformance.
Regards,
=> 874133: Need to update the UG documentation.

File-Formats/PDF/Working-with-action.md
Updated UG documentation content for PdfRemoteGoToAction support.
=> 874816 : UG Documentation for PdfRemoteGoToAction support.

File-Formats/Presentation/Working-with-images.md
HI All,
Crop value modified.
Regards
Venkatesh
=> ES-864081 Crop value modify 

File-Formats/XlsIO/Overview.md
Hi @MallikaRK,
Worked on description too long for FF excel.
Regards,
Sharly A.
=> SEO-180850-File-Format-changes

File-Formats/PDF/Working-with-OCR/Troubleshooting.md
Hi team,
Here we resolved the UG Documentation staging error.
Regards
=> 876039: Resolve UG Documentation staging error.

File-Formats/PDF/Working-with-DigitalSignature.md
Hi team,
Here we resolved 'tabs' tag was never closed issue.
Regards,
Srihariharan G
=> 876039: 'tabs' tag was never closed issue resolved.

File-Formats/DocIO/Working-with-Table-Of-Contents.md
HI All,
Remove unwanted spaces in md file.
Regarsd
venkatesh
=> ES-865474- Remove unwanted spaces

File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md, File-Formats/PDF/Working-with-OCR/Troubleshooting.md
Hi team,
Here we resolved the UG Documentation staging error.
Regards
=> 876039: Resolve UG Documentation staging error. 

File-Formats/DocIO/Convert-Word-Document-to-Image-in-WPF.md, File-Formats/DocIO/Convert-Word-Document-to-PDF-in-Google-App-Engine.md, File-Formats/DocIO/Create-Word-Document-in-Azure-App-Service-Windows.md, File-Formats/PDF/Create-PDF-document-in-Azure-App-Service-Windows.md, File-Formats/PDF/Loading-and-saving-document/Open-and-save-PDF-document-in-Azure-App-Service-Windows.md, File-Formats/Presentation/Convert-PowerPoint-to-PDF-in-Azure-App-Service-Windows.md
Have worked on Page with Redirect.
Regards,
Yvone.
=> SEO-179769 FF Redirect UG

File-Formats/DocIO/Convert-Word-Document-to-Image-in-Azure-Functions-v4.md, File-Formats/DocIO/Convert-Word-Document-to-Image-in-WinUI.md, File-Formats/DocIO/Convert-Word-Document-to-PDF-in-AWS-Elastic-Beanstalk.md, File-Formats/DocIO/Convert-Word-Document-to-PDF-in-Azure-Functions-v1.md, File-Formats/DocIO/Convert-Word-Document-to-PDF-in-Azure-Functions-v4.md, File-Formats/DocIO/Create-Word-Document-in-Azure-App-Service-Linux.md
Have changed Page with Redirect links.
Regards,
Yvone.l
=> SEO-179769 FileFormat Page Redirect

File-Formats/PDF/Convert-HTML-To-PDF/features.md, File-Formats/PDF/Working-with-DigitalSignature.md
Hi team,
Here we added HTMLToPDF_UG_Vol1_2024 features.
Regards,
=> 875092: HTMLToPDF_UG_Vol1_2024.

File-Formats/DocIO/Working-with-Table-Of-Contents.md, File-Formats/Presentation/Working-with-images.md
Hi All,
Sample GitHub link added for Crop and TOC feature.
Regards,
Venkatesh
=> ES-865474  Sample GitHub link added for Crop and TOC feature

File-Formats/PDF/Working-with-action.md
Hi team,
Here we added the proper code snippet in action section.
Regards,
Srihariharan G
=> 876129: Updated the code snippet in actions section.

File-Formats/PDF/Convert-HTML-To-PDF/features.md
Hi team,
Here we added the github sample for HTML to PDF features.
Regards,
=> 875092: Added github sample for HTML to PDF features.

File-Formats/DocIO/Convert-Word-Document-to-Image-in-MAUI.md, File-Formats/DocIO/Convert-Word-Document-to-PDF-in-MAUI.md, File-Formats/DocIO/Create-Word-document-in-MAUI.md, File-Formats/DocIO/Open-and-save-Word-document-in-MAUI.md
Task link - https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/877994
Revamp the UG for .NET MAUI and Xamarin for the helper files in both DocIO
=> ES-877994 - Revamp the UG for .NET MAUI and Xamarin for the helper files in both DocIO

File-Formats/DocIO/Create-Word-document-in-MAUI.md
Refer to the master PR - https://github.com/syncfusion-content/fileformat-docs/pull/1995
=> ES-877994 Moved the helper file in .NET MAUI in DocIO

File-Formats/DocIO/Open-and-save-Word-document-in-MAUI.md
Task link - https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/877994
Revamp the UG for .NET MAUI in DocIO.
=> ES-877994 - Revamp the UG for .NET MAUI in DocIO 

File-Formats/PDF/Convert-HTML-To-PDF/aws.md
Hi team,
Here we revamped the UG documentation in HTML to PDF AWS.
Regards,
Srihariharan G
=> 878666: Need to revamp the UG documentation in HTML to PDF AWS.

File-Formats/installation/web-installer/how-to-download.md
Hi @MallikaRK,
Worked on ff changes.
Regards,
Sharly A.
=> SEO-180850-FF-Changes-

File-Formats/Presentation/create-read-edit-powerpoint-files-in-uwp.md
Hi @MallikaRK ,
Kindly review the changes.
Regards,
Edith.
=> SEO-180844-page-with-redirect-FF

File-Formats/DocIO/Working-with-Word-document.md
Task link - https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/875351
Modify built-in document properties in a Word document
=> ES-875351 - Modify built-in document properties in a Word document

File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
Hi team,
Here we added "There was an error opening this document. This file is already open or in use by another application." trouble shooting in the HTML to PDF converter.
Regards,
=> 882858: Added trouble shooting in the HTML to PDF converter.

File-Formats/PDF/Working-with-OCR/Troubleshooting.md
Hi team,
Here we added Default path reference for Syncfusion OCR packages.
Regards,
=> 883086: Update Default path reference for Syncfusion OCR packages.

File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
Hi team,
Here we added HTML to PDF performance benchmark in UG.
Regards,
=> 881424: Added HTML to PDF performance benchmark in UG.

File-Formats/DocIO/FAQ.md, File-Formats/Presentation/Convert-PowerPoint-to-Image-in-AWS.md, File-Formats/Presentation/Convert-PowerPoint-to-Image-in-Azure.md, File-Formats/Presentation/Convert-PowerPoint-to-Image-in-Google-Cloud-Platform.md, File-Formats/Presentation/Convert-PowerPoint-to-PDF-in-AWS.md, File-Formats/Presentation/Convert-PowerPoint-to-PDF-in-Azure.md, File-Formats/Presentation/Convert-PowerPoint-to-PDF-in-Google-Cloud-Platform.md
Task link - https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/881285/
=> ES-881285 - Verified the hyperlinks of file format

File-Formats/Presentation/Working-with-Slide.md
Add UG content on merge slide with source formatting
Task link - https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/861532
=> ES-861532 - Add UG content on merge slide with source formatting

File-Formats/DocIO/mail-merge/mail-merge-events.md
Title | Description
-- | --
Task Category | Page with Redirect|
Content Task Link/Mail Screenshot | NA|
Hotfix | https://github.com/syncfusion-content/fileformat-docs/pull/2172|
Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/187645/|
Work link | https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B5956DB12-BF41-423F-9337-A60CF7314B63%7D&file=Yvone.xlsx&action=default&mobileredirect=true |
Changes Made | Reason for change | Reason for not identifying earlier
-- | -- | --
Page with Redirect | To avoid redirection 301 or 302 links, providing direct links. |  
Regards,
Yvone.
=> SEO-187645 File Format Page Redirect

File-Formats/PDF/Supported-and-Unsupported-Features.md, File-Formats/PDF/Working-with-Attachments.md, File-Formats/PDF/Working-with-Brushes.md, File-Formats/PDF/Working-with-HyperLinks.md, File-Formats/PDF/Working-with-Watermarks.md, File-Formats/PDF/Working-with-action.md
Title | Description
-- | --
Task Category | Description missing|
Content Task Link/Mail Screenshot | NA|
Hotfix | https://github.com/syncfusion-content/fileformat-docs/pull/2168|
Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/187125/|
Work link | https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B53B8CB63-6382-483B-9C55-34142FAB52A7%7D&file=Yvone.xlsx&action=default&mobileredirect=true |
Changes Made | Reason for change | Reason for not identifying earlier
-- | -- | --
Changed description | to improve CTR and helps to summarize page content |  
Regards,
Yvone.
=> SEO-187125 FF PDF Description Missing
