File-Formats/DocIO/Accepting-or-Rejecting-Track-Changes.md, File-Formats/DocIO/Applying-Watermark.md, File-Formats/DocIO/Create-Word-document-in-ASP-NET-Core.md, File-Formats/DocIO/Create-Word-document-in-ASP-NET-MVC.md, File-Formats/DocIO/Create-Word-document-in-ASP-NET.md, File-Formats/DocIO/Create-Word-document-in-Blazor.md, File-Formats/DocIO/Create-Word-document-in-Linux.md, File-Formats/DocIO/Create-Word-document-in-MAUI.md, File-Formats/DocIO/Create-Word-document-in-Mac.md, File-Formats/DocIO/Create-Word-document-in-UWP.md, File-Formats/DocIO/Create-Word-document-in-WPF.md, File-Formats/DocIO/Create-Word-document-in-WinUI.md, File-Formats/DocIO/Create-Word-document-in-Windows-Forms.md, File-Formats/DocIO/Create-Word-document-in-Xamarin.md, File-Formats/DocIO/Getting-Started.md, File-Formats/DocIO/Loading-and-Saving-document.md, File-Formats/DocIO/Working-With-Content-Controls.md, File-Formats/DocIO/Working-with-Charts.md, File-Formats/DocIO/Working-with-Macros.md, File-Formats/DocIO/Working-with-Mathematical-Equation.md, File-Formats/DocIO/Working-with-Paragraph.md, File-Formats/DocIO/Working-with-Sections.md, File-Formats/DocIO/Working-with-Shapes.md, File-Formats/DocIO/Working-with-Tables.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-62548">https://syncfusion.atlassian.net/browse/WF-62548</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
</td>
</tr>
<tr>
<td>
Changes done
</td>
<td>
Added GitHub sample link in UG documentation in below pages, <br/>
- Charts
- Content-Controls
- Getting-Started
- Macros
- Mathematical-Equation
- Paragraphs
- Read-and-Save-document
- Sections
- Shapes
- Tables
- Track-Changes
- Watermark
</td>
</tr>
</table>
=> WF-62548-Add GitHub sample link in UG documentation

File-Formats/DocIO/Assemblies-Required.md, File-Formats/DocIO/NuGet-Packages-Required.md, File-Formats/Presentation/Assemblies-Required.md, File-Formats/Presentation/NuGet-Packages-Required.md
<h4 id="feature-description">Kindly review the below merge request and let me know if you have any concerns,</h4>
<table style="width: 155px;">
<tbody>
<tr style="height: 86px;">
<td style="width: 37.7396px; height: 86px;">
<h4 id="feature-description">Task link</h4>
</td>
<td style="width: 121.26px; height: 86px;">
<p><a href="https://syncfusion.atlassian.net/browse/WF-62494" rel="nofollow">https://syncfusion.atlassian.net/browse/WF-62494</a></p>
</td>
</tr>
<tr style="height: 56.7917px;">
<td style="width: 37.7396px; height: 56.7917px;">
<h4 id="feature-description">Description</h4>
</td>
<td style="width: 121.26px; height: 56.7917px;">Removed .NET MAUI limitation in UG documentation</td>
</tr>
<tr style="height: 88px;">
<td style="width: 37.7396px; height: 88px;">
<h4 …
=> WF-62494-Removed .NET MAUI limitation in UG documentation

File-Formats/DocIO/Getting-Started.md, File-Formats/DocIO/Working-with-Fields.md, File-Formats/DocIO/Working-with-Word-document.md, File-Formats/DocIO/html.md, File-Formats/DocIO/mail-merge/mail-merge-events.md, File-Formats/DocIO/mail-merge/mail-merge-for-group.md, File-Formats/DocIO/mail-merge/mail-merge-for-nested-groups.md, File-Formats/DocIO/mail-merge/mail-merge-options.md, File-Formats/DocIO/mail-merge/simple-mail-merge.md, File-Formats/DocIO/rtf.md, File-Formats/DocIO/text.md, File-Formats/DocIO/word-file-formats.md, File-Formats/DocIO/word-to-epub.md, File-Formats/DocIO/word-to-image.md, File-Formats/DocIO/word-to-odt.md, File-Formats/DocIO/working-with-mail-merge.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-62692">https://syncfusion.atlassian.net/browse/WF-62692</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
</td>
</tr>
<tr>
<td>
Changes done
</td>
<td>
Added GitHub sample link in UG documentation in below pages, 
<p></p>
- Fields
- Mail-Merge
- Word-document
- RTF-conversion
- Text-file-conversion
- HTML-conversion
- Word-file-formats
- Word-to-EPUB-conversion
- Word-to-Image-conversion
- Word-to-ODT-conversion
</td>
</tr>
</table>
=> WF-62692-Add UG documentation changes for GitHub link

File-Formats/DocIO/Working-with-Paragraph.md, File-Formats/DocIO/Working-with-Word-document.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-62949">https://syncfusion.atlassian.net/browse/WF-62949</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Divide the existing Working With Word Document UG documentation as sub page documents.
</td>
</tr>
<tr>
<td>
Changes done
</td>
<td>
Added redirection links to the existing url in Word document page in order to avoid broken links, 
<p></p>
- Iterating Word document elements
- Merging Word Documents
- Print Word documents
- Split Word documents
- Working with Styles
</td>
</tr>
</table>
=> WF-62949-Added redirection links to the existing Url in Word document page

File-Formats/PDF/Working-with-Text-Extraction.md
Added information about using the TextLineCollection in ASP.NET Core instead of TextLine. Code example is also added for ASP.NET Core platform under the topics “Working with Lines” and “Working with words”.
=> EJDOTNETCORE-3559 - Correct the text extraction with bounds documentation for ASP.NET Core platform

File-Formats/DocIO/Working-with-Shapes.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-63104">https://syncfusion.atlassian.net/browse/WF-63104</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Add UG documentation to get or set internal margins for shapes in Word document.
</td>
</tr>
<tr>
<td>
Solution
</td>
<td>
Added code snippet to set internal margins for shapes in all platforms. <br/>
</td>
</tr>
</table>
=> WF-63104-Add UG documentation to get or set internal margins for shapes in Word document

File-Formats/DocIO/word-to-pdf.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-63118">https://syncfusion.atlassian.net/browse/WF-63118</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Update a UG documentation with Underline style and Strikethrough support
</td>
</tr>
<tr>
<td>
Solution
</td>
<td>
Updated underline styles details in supported and unsupported elements in Word to PDF page. <br/>
</td>
</tr>
</table>
=> WF-63118-Update a UG documentation with Underline style and Strikethrough support

File-Formats/DocIO/FAQ.md, File-Formats/DocIO/Working-with-Charts.md, File-Formats/DocIO/Working-with-Paragraph.md, File-Formats/DocIO/mail-merge/mail-merge-events.md, File-Formats/DocIO/mail-merge/mail-merge-for-nested-groups.md, File-Formats/DocIO/mail-merge/mail-merge-options.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-63101">https://syncfusion.atlassian.net/browse/WF-63101</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
</td>
</tr>
<tr>
<td>
Changes done
</td>
<td>
- Added GitHub sample link in UG documentation for new features.
- Corrected the mistakes in the code snippet in UG documentation.
- Updated the proper GitHub sample link.
- Corrected the hyperlink in FAQ page.
</td>
</tr>
</table>
=> WF-63101-Link the GitHub samples in UG new features documentation

File-Formats/DocIO/word-to-image.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-64205">https://syncfusion.atlassian.net/browse/WF-64205</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Add UG document for all the overloads in Word to image conversion.
</td>
</tr>
<tr>
<td>
Solution
</td>
<td>
Added code snippet in Word to image page in all platforms. 
- Convert the entire Word to images
- Convert first page of Word to image
- Convert a specific range of pages in Word to an image
</td>
</tr>
<tr>
<td>
</td>
<td>
Not yet
</td>
</tr>
</table>
=> WF-64205-Add UG for entire pages, first page and specific range of pages in Word to image conversion

File-Formats/DocIO/word-to-pdf.md
<table>
<tbody>
<tr>
<td>
</td>
<td>
<p><a href="https://syncfusion.atlassian.net/browse/WF-64286">https://syncfusion.atlassian.net/browse/WF-64286</a></p>
</td>
</tr>
<tr>
<td>
</td>
<td>
<p>Update a UG documentation with Underline style and Strikethrough support</p>
</td>
</tr>
<tr>
<td>
</td>
<td>
<p>Remove underline styles details in unsupported elements in Word to PDF page.</p>
</td>
</tr>
</tbody>
</table>
=> WF-64286-Update a UG documentation with Underline style and Strikethrough support

File-Formats/PDF/Working-with-DigitalSignature.md, File-Formats/PDF/Working-with-OCR/Dot-NET-Core.md, File-Formats/PDF/Working-with-OCR/Dot-NET-Framework.md, File-Formats/PDF/Working-with-Shapes.md
Hi Sir, 
I have added the forward slash ("/") instead of backward slash ("\") in PDF UG documentation (OCR). Also I have added some missing items "" and certificate file name for the below topics, 
- Draw arc in an existing PDF document (added " in file name) 
- Adding digital signature using stream (added certificate name) 
Kindly review and merge the changes. 
Regards,
Sowmiya L
=> WF-64353 - Added the forward slash ("/") instead of backward slash ("\") - Hotfix

File-Formats/PDF/Working-with-OCR/Dot-NET-Core.md
Hi All, 
We have changed the folder structure in GitHub OCR and due to this link changes, existing links are not working in PDF OCR UG documentation. So, I have changed the GitHub sample links and kindly review this. 
Regards,
Sowmiya L
=> EJDOTNETCORE-4238 - Modify the GitHub sample links in PDF OCR topic - Hotfix

File-Formats/DocIO/convert-word-document-to-markdown-in-csharp.md
<table>
<tbody>
<tr>
<td>Task Link</td>
<td>https://syncfusion.atlassian.net/browse/WF-63881</td>
</tr>
<tr>
<td>Description</td>
<td>Add UG document for&nbsp;Word to Markdown Conversion</td>
</tr>
<tr>
<td>Solution</td>
<td>Modified table points to preserve sentence inside table cell</td>
</tr>
<tr>
<td>Content review confirmation</td>
<td>Yes</td>
</tr>
</tbody>
</table>
=> WF-64951-Add-UG-document-to-convert-Word-document-into-Markdown

File-Formats/DocIO/Supported-and-Unsupported-Features.md, File-Formats/DocIO/word-to-pdf.md, File-Formats/Presentation/Presentation-to-PDF.md, File-Formats/Presentation/Presentation-to-image.md, File-Formats/Presentation/Supported-and-Unsupported-Features.md
<table>
<tr>
<td>
Task Link
</td>
<td>
<a href="https://syncfusion.atlassian.net/browse/WF-65166">https://syncfusion.atlassian.net/browse/WF-65166</a>
</td>
</tr>
<tr>
<td>
Description
</td>
<td>
Remove note from DocIO and Presentation documentation pages.
</td>
</tr>
<tr>
<td>
Solution
</td>
<td>
Remove note regarding Word/PPTX to PDF/image not support in Blazor WASM.
</td>
</tr>
</table>
[WF-65166]: https://syncfusion.atlassian.net/browse/WF-65166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WF-65166]: https://syncfusion.atlassian.net/browse/WF-65166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WF-65166-Remove note regarding Word/PPTX to PDF/image not support in Blazor WASM from UG

File-Formats/DocIO/FAQ.md, File-Formats/DocIO/mail-merge/mail-merge-events.md, File-Formats/DocIO/word-to-pdf.md
<tbody>
<tr>
<td style="width: 349.306px;">(https://syncfusion.atlassian.net/browse/WF-57277)</td>
</tr>
<tr>
<td style="width: 349.306px;">Added Blazor Server side in Word to PDF namespace list in DocIO UG</td>
</tr>
<tr>
<td style="width: 349.306px;">Added Blazor Server side in Word to PDF namespace list, Added license clearance information to use Microsoft fonts, Added a note in UG about how to insert multiple body items using mergefield event handler</td>
</tr>
<tr>
</tr>
</tbody>
</table>
=> WF-57277-Made UG changes to add missed statements

File-Formats/PDF/Working-with-Annotations.md, File-Formats/PDF/Working-with-HyperLinks.md, File-Formats/PDF/Working-with-forms.md
Hi All,
Kindly review the changes and let me know your feedback for the same. Please find the changes from below,
**Flattening redaction annotation**
- Added the code snippet for flattening redaction annotation in an existing PDF document.
- In ASP.NET Core platform, we need to add "loadedDocument.Redact();" code to flatten the PDF document and added this line also.
- In notes tab, added the details about assemblies required.
**Modify the redaction annotation**
To modify the redaction annotation in ASP.NET Core, we need to use "Syncfusion.Pdf.Imaging.Portable" assemblies and "loadedDocument.Redact();" code. Added this code and information in notes tab.
Regards,
Sowmiya L
=> EJDOTNETCORE-4045 - Add code example for flatten redaction annotation and update code for modify redaction annotation - Hotfix

File-Formats-toc.html, File-Formats/PDF-to-image/Convert-PDF-file-to-Image-in-ASP-NET-MVC.md, File-Formats/PDF-to-image/Convert-PDF-to-Image.md, File-Formats/PDF-to-image/Converting-PDF-pages-into-Images-in-ASP-NET-Core.md, File-Formats/PDF-to-image/Converting-PDF-pages-into-Images-in-ASP-NET-MVC.md, File-Formats/PDF-to-image/Converting-PDF-pages-into-Images-in-Blazor.md, File-Formats/PDF/Working-with-Document-Conversions.md
UG Content for PdfToImageConverter
=> UG Content for PdfToImageConverter

File-Formats-toc.html, File-Formats/DocIO/Applying-Watermark.md, File-Formats/DocIO/word-to-pdf-linux-docker.md
Hi all,
- Added **Word To PDF sample** page in outside too.
- Added the ASP.NET core code snippet for **Picture watermark** DocIO sample.
- Added HarfBuzzSharp.NativeAssets.Linux NuGet link in **Word To PDF Docker sample** page.
Regards,
Dharanitharan A
=> ES-846833-Added HarfBuzzNuGet in UG Word document to PDF Conversion in Linux Docker & Separate Word to PDF as separate page

File-Formats/PDF/Convert-HTML-To-PDF/features.md, File-Formats/PDF/Working-with-DigitalSignature.md, File-Formats/PDF/Working-with-Document.md
Hi Sir,
I have added the GitHub sample link for 2023 Volume 3 Release. Kindly review this.
Regards,
Jeyalakshmi T
=> 848818- Added the GitHub sample link for 2023 Volume 3 Release

File-Formats/PDF/Working-with-OCR/MAC.md, File-Formats/PDF/Working-with-OCR/Troubleshooting.md
Hi All,
I have added the sample for perform OCR in Mac. Kindly review this.
Regards,
=> 848740 : Need to update UG documentation in OCR section

File-Formats/PDF/Convert-HTML-To-PDF/features.md, File-Formats/PDF/Working-with-OCR/Features.md
Hi All, 
I have updated the GitHub sample links for volume 3 features. Kindly review this and merge. 
Regards,
Sowmiya L
=> 849836 - Updated the volume3 features code example with GitHub samples - Hotfix

File-Formats-toc.html, File-Formats/XlsIO/faqs/how-to-set-rounded-corner-for-chart-in-excel-document.md
I have added UG for the rounded corner of the chart. Kindly review the changes.
Regards,
Kurmitha
=> 850175 - Add the UG for Rounded Corner of the Chart - HF

File-Formats/Presentation/Working-with-Charts.md
Add working with chart YouTube video link in Working-with-Charts.md file
=> ES-848208 Add working with chart YouTube video link in UG

File-Formats/Presentation/Presentation-to-image.md
Added presentation to image conversion youtube link in UG
=> ES 848208 Add presentation to image conversion Youtube link in UG

File-Formats-toc.html, File-Formats/DocIO/Convert-Word-Document-to-PDF-in-AWS.md, File-Formats/Presentation/Convert-PowerPoint-to-Image-in-AWS.md, File-Formats/Presentation/Convert-PowerPoint-to-PDF-in-AWS.md
HI All,
1. Move PowerPoint to PDF as separate TOC.
2. Change the name **Word Document to Image** to **Word to Image**.
3. Added the NuGet link in overview of AWS in Presentation product.
5. Change the casing for Presentation product.
Task Link: <a href ="https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/852346">Move PowerPoint to PDF as separate TOC</a>
Regards
Venkatesh
=> ES-852346 Move PowerPoint to PDF as separate TOC

File-Formats/DocIO/word-file-formats.md
Hi All,
I completed draft work for CompatibilityMode API in UG
Task Link: <a href="https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/852932">Add CompatibilityMode API in UG</a>
=> ES-852932 Save Word in old compatibility

File-Formats/PDF/Split-Documents.md
Hi All,
Added UG documentation for remove Unused Resources when Splitting PDF Documents.
Regards,
Jeyalakshmi T
=> 861628 -Remove Unused Resources when Splitting PDF Documents

File-Formats/DocIO/word-to-image.md, File-Formats/DocIO/word-to-pdf.md
Please refer to the below development MR
https://github.com/syncfusion-content/fileformat-docs/pull/1713
=> ES-853397-Added github sample link for the fallback font code snippet

File-Formats/DocIO/Working-with-LaTeX.md
HI All
Modify the syntax in LaTeX.
Regards
Venkatesh
=> ES 861360 Modify the syntax in LaTeX

File-Formats/PDF/Working-with-PDF-Templates.md
Hi team
I have added proper save method for UG sample.
Regards,
=> 864918: Update proper save method.

File-Formats-toc.html
Hi team,
I have revamped the missed HTML to PDF in AWS documentation.
Regards,
=> 866213: Revamping the missed HTML to PDF in AWS documentation.

File-Formats/PDF/Working-with-OCR/how-to-perform-ocr-for-a-pdf-document-using-cSharp-and-VB.md
Have worked on Page with Redirect links.
Regards,
Yvone.
=> SEO-178115 File Format Redirect

File-Formats/Presentation/Presentation-to-image.md
<p dir="auto">Kindly review the below pull request and let me know your feedback.</p>
<div dir="auto">
<div dir="auto">
<div dir="auto">
<table style="width: 691.052px;">
<tbody>
<tr>
<td style="width: 62px;">
<p dir="auto">Task Link</p>
</td>
<td style="width: 615.052px;">
<p dir="auto"><a href="https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/260166">https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/260166</a>&nbsp;</p>
</td>
</tr>
<tr>
<td style="width: 62px;">
<p dir="auto">Description</p>
</td>
<td style="width: 615.052px;">
<p dir="auto">Added the cross platform code for below samples,</p>
<ul>
<li dir="auto">PowerPoint Presentation to images</li>
<li dir="auto">Font substitution for unavailable fonts</li> …
=> ES-818185-Added cross platform code for PPTX to Image in Presentation

File-Formats/DocIO/Working-with-LaTeX.md
Kindly review the below pull request and let me know your feedback.
<div dir="auto">
<div dir="auto">
<div dir="auto">
<table>
<tbody>
<tr style="height: 35px;">
<td style="height: 35px;">
<p dir="auto">Task Link</p>
</td>
<td style="height: 35px;">
<p dir="auto"><a href="https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/260166#4123188">UG documentation 260166: Modify the existing code snippets in PPTX to image conversion in UG - Boards (azure.com)</a></p>
</td>
</tr>
<tr style="height: 35.3333px;">
<td style="height: 35.3333px;">
<p dir="auto">Description</p>
</td>
<td style="height: 35.3333px;">
<p dir="auto">Resolved curly braces in LaTeX UG DocIO</p>
</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
=> ES-260166-Resolved latex curly braces in DocIO

File-Formats/PDF/Split-Documents.md
Hi team,
Here we resolved the liquid syntax error.
Regards,
Srihariharan G
=> 867572: Resolved liquid syntax error.

File-Formats/DocIO/word-to-pdf.md
Show warning for unsupported element during Word to PDF
=> ES-261786 - Show warning for unsupported element during Word to PDF

File-Formats/DocIO/Working-with-LaTeX.md
=> ES-868708-Added Apply Math Justification in DocIO

File-Formats/DocIO/html.md, File-Formats/DocIO/word-to-pdf.md
Task link - https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/865560
Added content for HTMLExportBodyContentAlone API
Task link - https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/261786
Show warning for unsupported element during Word to PDF
=> ES-865560- Added content for HTMLExportBodyContentAlone API

File-Formats/XlsIO/Worksheet-Rows-and-Columns-Manipulation.md
Hi @Mohan2401,
I have added a  UG note for explaining hidden row or columns gets visible when autofit rows or columns. Kindly review the changes.
Regards,
Kurmitha M.
=> 868245- Add UG note for explaining hidden row or columns gets visible when autofit rows or columns -Hotfix

File-Formats/DocIO/word-to-pdf.md, File-Formats/Presentation/Charts/Chart-Data-Labels.md, File-Formats/Presentation/Charts/Chart-Legend.md
=> ES-868708-Add the KB links for DocIO and Presentation

File-Formats/DocIO/Working-with-LaTeX.md
Task link - https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/868758
Resolved issues
=> ES_868758 - Add UG documentation for applying math justification

File-Formats/Presentation/Working-with-Slide.md
Hi All,
Modify the existing code slide.Add API in Presentation.
Task Link: <a href="https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/868571">Modify the existing code snippet for ISlide.Add(ISlide clonedSlide, PasteOptions pasteOptions, IPresentation sourcePresentation) API in UG documentation</a>
Regards
Venkatesh
=> ES-868571 Modify the existing code slide.Add API in Presentation.

File-Formats/DocIO/Working-with-Charts.md
HI All,
UG draft work completed for create a chart in a Word  document form database.
Task Link : <a href="https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/259772">How to create chart in Word document with data from database</a>
Regards
Venkatesh
=> ES-259772 Create a chart in a Word document form database

File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
Hi team,
Here we added Zombie process are not closed by default troubleshooting.
Regards,
=> 873331: Zombie process are not closed by default from chrome headless in Linux platform.

File-Formats/PDF/Working-with-OCR/Troubleshooting.md
Hi team,
Here we resolved the UG Documentation staging error.
Regards
=> 876039: Resolve UG Documentation staging error.

File-Formats/DocIO/FAQ.md
Task link - https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/259460
Add FAQ about why content control not preserving as like editable form fields in the PDF document when enabling PreserveFormFields
Hotfix - https://github.com/syncfusion-content/fileformat-docs/pull/1916
=> ES-259460-Add FAQ about why content control not preserving as like editable form fields in the PDF document when enabling PreserveFormFields

File-Formats/PDF/Convert-HTML-To-PDF/Convert-HTML-to-PDF-in-AWS-Elastic-Beanstalk.md, File-Formats/PDF/Convert-HTML-To-PDF/Convert-HTML-to-PDF-in-AWS-Lambda.md, File-Formats/Presentation/Convert-PowerPoint-to-Image-in-MAUI.md, File-Formats/Presentation/Convert-PowerPoint-to-Image-in-Xamarin.md, File-Formats/Presentation/Convert-PowerPoint-to-PDF-in-MAUI.md, File-Formats/Presentation/Convert-PowerPoint-to-PDF-in-Xamarin.md, File-Formats/Presentation/Presentation-to-image.md
I have worked on changing redirection links, please review.
Regards,
Scholar.
=> SEO-180837-File-Formats-Redirection

File-Formats/PDF/Working-with-OCR/Working-with-OCR.md
Hi team,
Here we updated the correct URL link for navigating to MAC getting started.
Regards,
Srihariharan G
=> 876381: update the correct url link for navigating to MAC getting started.

File-Formats/XlsIO/Create-read-edit-excel-files-in-maui-c-sharp.md
Modified a sample path for maui samples. Kindly review the changes.
Regards,
Kurmitha
=> 873967_Modify the Maui sample path

File-Formats/PDF/Convert-HTML-To-PDF/features.md
Hi team,
Here we added the github sample for HTML to PDF features.
Regards,
=> 875092: Added github sample for HTML to PDF features.

File-Formats/DocIO/Convert-Word-Document-to-Image-in-MAUI.md, File-Formats/DocIO/Convert-Word-Document-to-PDF-in-MAUI.md, File-Formats/DocIO/Create-Word-document-in-MAUI.md, File-Formats/DocIO/Open-and-save-Word-document-in-MAUI.md
Task link -  https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/877994
Revamp the UG for .NET MAUI and Xamarin for the helper files in both DocIO
=> ES-877994 - Revamp the UG for .NET MAUI and Xamarin for the helper files in both DocIO

File-Formats/PDF/Working-with-Watermarks.md
Hi team,
Here we added watermark annotation and remove watermark annotation UG documents.
Regards,
=> 880343: Need to update the PDF section in the UG documentation.

File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
Hi team,
Here we added Failed to load Chrome DLL exception occurs in Windows 7/8 and Windows Server 2008,2012 machine issue in troubleshooting page.
Regards,
=> 880908: Failed to load Chrome DLL exception troubleshoot.

File-Formats/PDF/Convert-HTML-To-PDF/troubleshooting.md
Hi team,
Here we added Failed to load Chrome DLL exception occurs in Windows 7/8 and Windows Server 2008,2012 machine issue in troubleshooting page.
Regards,
=> 880908: Update proper URL links fpr troubleshooting.

File-Formats/PDF/Working-with-OCR/Troubleshooting.md
hi team,
Here we added OCR not working on Docker net 8.0: Exception has been thrown by target of an invocation in troubleshooting page.
Regards,
=> 881103: OCR not working on Docker net 8.0: Exception.

File-Formats/Presentation/Working-with-find-and-replace.md
Task link - https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/868620
In this PR, i have added note for Find and replace in Presentation
=> ES-868620-Add note for Find and replace in Presentation

File-Formats/XlsIO/Working-with-Data.md
Hi @Mohan2401,
I have modified a content for using combination of ExcelExportDataTableOptions. Kindly review the changes.
Regards,
Kurmitha M.
=> 869952 - Modify UG content for using combination of ExcelExportDataTableOptions

File-Formats/XlsIO/Working-with-Data.md
Added notes for importing data with string type.
=> 871981 - Add UG notes for importing data with string type

File-Formats/XlsIO/Working-with-Template-Markers.md
Added a UG note for template marker usage.
=> 869954 - Add a UG note for template marker usage

File-Formats-toc.html, File-Formats/XlsIO/FAQ.md, File-Formats/XlsIO/faqs/how-to-hide-columns-using-column-name.md, File-Formats/XlsIO/faqs/how-to-resolve-performance-issue-when-deleting-a-large-number-of-rows.md
Added FAQ for hide columns using column name.
=> 881834 - Add FAQ for hide columns using column name

File-Formats/PDF/Working-with-Redaction.md
Hi team,
Here we added UG for "Find text by regular expression pattern and redact it from PDF document".
Regards,
=> 884238: Find text by regular expression pattern and redact it from PDF document.

File-Formats-toc.html, File-Formats/XlsIO/FAQ.md, File-Formats/XlsIO/faqs/how-to-convert-xls-document-to-xlsx-format-document.md
Added FAQ for how to convert xls to xlsx document.
=> 882003 - Add FAQ for how to convert xls to xlsx document.

File-Formats/XlsIO/Working-with-Charts.md
Hi @Mohan2401,
I have added a content for gradient fill in chart. Kindly review the changes.
Regards,
Ramya
=> 871974- Add the UG for gradient fill in chart

File-Formats/XlsIO/Worksheet-Cells-Manipulation.md
I have modified the hyperlink UG section. Kindly review the changes.
Regards,
Kurmitha M.
=> 882504- Split the hyperlink UG in XlsIO

File-Formats/PDF/Working-with-PDF-Conformance.md
Hi team,
Here we updated the conformance level for PDF to PDF/A conformance.
Regards,
=> update_conformance: Update the PDF to PDF/A conformance page.
